<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Console\Commands;

use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class CreateAdmin extends Command
{
    protected $signature = 'statalog:create-admin
                            {--name= : Admin full name}
                            {--email= : Admin email address}
                            {--password= : Admin password (min 8 chars)}';

    protected $description = 'Create an admin user for Statalog (self-hosted).';

    public function handle(): int
    {
        $name     = $this->option('name')     ?: $this->ask('Full name');
        $email    = $this->option('email')    ?: $this->askWithConfirmation('Email address', 'Confirm email');
        $password = $this->option('password') ?: $this->secretWithConfirmation('Password (min 8 chars)', 'Confirm password');

        $validator = Validator::make(compact('name', 'email', 'password'), [
            'name'     => ['required', 'string', 'max:255'],
            'email'    => ['required', 'email', 'max:255', 'unique:users,email'],
            'password' => ['required', 'string', 'min:8'],
        ]);

        if ($validator->fails()) {
            foreach ($validator->errors()->all() as $error) {
                $this->error($error);
            }
            return self::FAILURE;
        }

        $user = User::create([
            'name'              => $name,
            'email'             => $email,
            'password'          => Hash::make($password),
            'email_verified_at' => now(),
        ]);

        $this->info("Admin user created: {$user->email} (ID: {$user->id})");
        $this->line('You can now log in at ' . rtrim(config('app.url'), '/') . '/login');

        return self::SUCCESS;
    }

    private function askWithConfirmation(string $prompt, string $confirmPrompt): string
    {
        while (true) {
            $first  = $this->ask($prompt);
            $second = $this->ask($confirmPrompt);

            if ($first === $second) {
                return $first;
            }

            $this->error('Values do not match. Please try again.');
        }
    }

    private function secretWithConfirmation(string $prompt, string $confirmPrompt): string
    {
        while (true) {
            $first  = $this->secret($prompt);
            $second = $this->secret($confirmPrompt);

            if ($first === $second) {
                return $first;
            }

            $this->error('Passwords do not match. Please try again.');
        }
    }
}
