<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Services;

use MaxMind\Db\Reader;

class GeoIpService
{
    private ?Reader $reader = null;

    public function lookup(string $ip): array
    {
        try {
            $reader = $this->getReader();

            if ($reader === null) {
                return ['country' => '', 'region' => '', 'city' => '', 'latitude' => 0.0, 'longitude' => 0.0];
            }

            $record = $reader->get($ip);

            if ($record === null) {
                return ['country' => '', 'region' => '', 'city' => '', 'latitude' => 0.0, 'longitude' => 0.0];
            }

            return [
                'country'   => $record['country']['iso_code'] ?? '',
                'region'    => $record['subdivisions'][0]['iso_code'] ?? '',
                'city'      => $record['city']['names']['en'] ?? '',
                'latitude'  => (float) ($record['location']['latitude'] ?? 0),
                'longitude' => (float) ($record['location']['longitude'] ?? 0),
            ];
        } catch (\Throwable) {
            return ['country' => '', 'region' => '', 'city' => '', 'latitude' => 0.0, 'longitude' => 0.0];
        }
    }

    private function getReader(): ?Reader
    {
        if ($this->reader !== null) {
            return $this->reader;
        }

        $path = config('statalog.geoip_database');

        if (!$path || !file_exists($path)) {
            return null;
        }

        $this->reader = new Reader($path);

        return $this->reader;
    }
}
