<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Services;

use App\Models\Setting;
use Illuminate\Support\Facades\Cache;

class SettingsService
{
    protected const CACHE_TTL = 300;

    public function get(string $key, mixed $default = null): mixed
    {
        $settings = $this->all();
        return $settings[$key] ?? $default;
    }

    public function set(string $key, mixed $value, string $group = 'general', bool $encrypted = false): void
    {
        $storeValue = $encrypted ? encrypt($value) : $value;

        Setting::updateOrCreate(
            ['key' => $key],
            [
                'value'        => $storeValue,
                'is_encrypted' => $encrypted,
                'group'        => $group,
            ]
        );

        $this->clearCache();
    }

    public function all(): array
    {
        return Cache::remember($this->cacheKey(), self::CACHE_TTL, function () {
            $settings = [];
            foreach (Setting::all() as $setting) {
                $value = $setting->value;
                if ($setting->is_encrypted && $value) {
                    try {
                        $value = decrypt($value);
                    } catch (\Exception $e) {
                        $value = null;
                    }
                }
                $settings[$setting->key] = $value;
            }
            return $settings;
        });
    }

    public function group(string $group): array
    {
        $all = $this->all();
        $result = [];
        $keys = Setting::where('group', $group)->pluck('key')->toArray();
        foreach ($keys as $key) {
            $result[$key] = $all[$key] ?? null;
        }
        return $result;
    }

    public function clearCache(): void
    {
        Cache::forget($this->cacheKey());
    }

    protected function cacheKey(): string
    {
        $userId = auth()->id() ?? 'guest';
        return "app_settings:user:{$userId}";
    }
}
