<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Services;

use function donatj\UserAgent\parse_user_agent;

class UserAgentService
{
    public function parse(string $userAgent, int $screenWidth = 0): array
    {
        if (empty($userAgent)) {
            return [
                'browser'         => '',
                'browser_version' => '',
                'os'              => '',
                'os_version'      => '',
                'device_type'     => 'unknown',
            ];
        }

        try {
            $parsed = parse_user_agent($userAgent);
        } catch (\Throwable) {
            $parsed = ['browser' => null, 'version' => null, 'platform' => null];
        }

        $browser = $parsed['browser'] ?? '';
        $os      = $parsed['platform'] ?? '';

        if ($browser === '' || $browser === null) {
            $browser = $this->detectBrowserFallback($userAgent);
        }
        if ($os === '' || $os === null) {
            $os = $this->detectOsFallback($userAgent);
        }

        return [
            'browser'         => $browser,
            'browser_version' => $parsed['version'] ?? '',
            'os'              => $os,
            'os_version'      => '',
            'device_type'     => $this->detectDeviceType($userAgent, $screenWidth),
        ];
    }

    private function detectOsFallback(string $ua): string
    {
        if (str_contains($ua, 'Windows NT'))          return 'Windows';
        if (str_contains($ua, 'Macintosh') || str_contains($ua, 'Mac OS X')) return 'macOS';
        if (str_contains($ua, 'CrOS'))                return 'Chrome OS';
        if (str_contains($ua, 'Android'))             return 'Android';
        if (str_contains($ua, 'iPhone') || str_contains($ua, 'iPad') || str_contains($ua, 'iPod')) return 'iOS';
        if (str_contains($ua, 'Linux'))               return 'Linux';
        return '';
    }

    private function detectBrowserFallback(string $ua): string
    {
        if (str_contains($ua, 'SamsungBrowser'))      return 'Samsung Browser';
        if (str_contains($ua, 'YaBrowser'))           return 'Yandex';
        if (str_contains($ua, 'OPR/') || str_contains($ua, 'OPiOS/')) return 'Opera';
        if (preg_match('/Edg[eA]?\//i', $ua))         return 'Edge';
        if (str_contains($ua, 'Chrome'))              return 'Chrome';
        if (str_contains($ua, 'Firefox'))             return 'Firefox';
        if (str_contains($ua, 'Safari'))              return 'Safari';
        return '';
    }

    private function detectDeviceType(string $userAgent, int $screenWidth): string
    {
        $ua = strtolower($userAgent);

        if (str_contains($ua, 'ipad') || str_contains($ua, 'tablet')) {
            return 'tablet';
        }

        if (
            str_contains($ua, 'mobile') ||
            str_contains($ua, 'iphone') ||
            str_contains($ua, 'ipod') ||
            (str_contains($ua, 'android') && !str_contains($ua, 'tablet'))
        ) {
            return 'mobile';
        }

        if ($screenWidth > 0 && $screenWidth < 768) {
            return 'mobile';
        }

        if ($screenWidth > 0 && $screenWidth < 1024) {
            return 'tablet';
        }

        return 'desktop';
    }
}
