<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Services;

use function donatj\UserAgent\parse_user_agent;

class UserAgentService
{
    public function parse(string $userAgent, int $screenWidth = 0): array
    {
        if (empty($userAgent)) {
            return [
                'browser'         => '',
                'browser_version' => '',
                'os'              => '',
                'os_version'      => '',
                'device_type'     => 'unknown',
            ];
        }

        try {
            $parsed = parse_user_agent($userAgent);
        } catch (\Throwable) {
            $parsed = ['browser' => null, 'version' => null, 'platform' => null];
        }

        return [
            'browser'         => $parsed['browser'] ?? '',
            'browser_version' => $parsed['version'] ?? '',
            'os'              => $parsed['platform'] ?? '',
            'os_version'      => '',
            'device_type'     => $this->detectDeviceType($userAgent, $screenWidth),
        ];
    }

    private function detectDeviceType(string $userAgent, int $screenWidth): string
    {
        $ua = strtolower($userAgent);

        if (str_contains($ua, 'ipad') || str_contains($ua, 'tablet')) {
            return 'tablet';
        }

        if (
            str_contains($ua, 'mobile') ||
            str_contains($ua, 'iphone') ||
            str_contains($ua, 'ipod') ||
            (str_contains($ua, 'android') && !str_contains($ua, 'tablet'))
        ) {
            return 'mobile';
        }

        if ($screenWidth > 0 && $screenWidth < 768) {
            return 'mobile';
        }

        if ($screenWidth > 0 && $screenWidth < 1024) {
            return 'tablet';
        }

        return 'desktop';
    }
}
