<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Repositories\AnalyticsRepository;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Redis;

class HealthController extends Controller
{
    public function __construct(private readonly AnalyticsRepository $analytics) {}

    public function index(): JsonResponse
    {
        $checks = [
            'clickhouse' => $this->checkClickhouse(),
            'redis'      => $this->checkRedis(),
        ];

        $allOk  = !in_array('error', $checks, true);
        $status = $allOk ? 200 : 503;

        return response()->json([
            'status'      => $allOk ? 'ok' : 'degraded',
            'environment' => app()->environment(),
            'services'    => $checks,
        ], $status);
    }

    private function checkClickhouse(): string
    {
        return $this->analytics->testConnection() ? 'ok' : 'error';
    }

    private function checkRedis(): string
    {
        try {
            return Redis::ping() === true || Redis::ping() === 'PONG' ? 'ok' : 'error';
        } catch (\Throwable) {
            return 'error';
        }
    }
}
