<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Jobs\ProcessAnalyticsHit;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class PixelController extends Controller
{
    // 1×1 transparent GIF
    private const GIF = 'R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';

    public function track(Request $request): Response
    {
        $siteId = trim($request->query('site', ''));
        $url    = trim($request->query('url', ''))
               ?: trim($request->header('Referer', ''));

        if ($siteId !== '') {
            ProcessAnalyticsHit::dispatch(
                payload: [
                    'site_id' => $siteId,
                    'type'    => 'pageview',
                    'url'     => $url,
                ],
                ip:        $request->ip() ?? '',
                userAgent: $request->userAgent() ?? '',
                dnt:       $request->header('DNT') === '1',
            );
        }

        return response(base64_decode(self::GIF), 200)
            ->header('Content-Type', 'image/gif')
            ->header('Cache-Control', 'no-store, no-cache, must-revalidate')
            ->header('Access-Control-Allow-Origin', '*');
    }
}
