<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Analytics Report — {{ $site->domain }}</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a2e; background: #fff; }

.page-header { border-bottom: 3px solid #5B6EF5; padding-bottom: 14px; margin-bottom: 22px; }
.page-header .site-name { font-size: 20px; font-weight: 700; color: #1a1a2e; }
.page-header .subtitle { font-size: 11px; color: #6b7280; margin-top: 3px; }
.page-header .logo { font-size: 10px; color: #9ca3af; text-align: right; }

.section { margin-bottom: 28px; }
.section-title { font-size: 14px; font-weight: 700; color: #1a1a2e; border-left: 3px solid #5B6EF5; padding-left: 8px; margin-bottom: 14px; }

/* Summary grid */
.stats-grid { display: table; width: 100%; border-collapse: separate; border-spacing: 8px; }
.stats-row  { display: table-row; }
.stat-cell  { display: table-cell; width: 20%; background: #f8f9fc; border: 1px solid #e5e7eb; border-radius: 6px; padding: 10px 12px; vertical-align: top; }
.stat-label { font-size: 10px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.04em; margin-bottom: 3px; }
.stat-value { font-size: 20px; font-weight: 700; color: #1a1a2e; }
.stat-trend { font-size: 10px; margin-top: 3px; }
.trend-up   { color: #16a34a; }
.trend-down { color: #dc2626; }
.trend-flat { color: #9ca3af; }

/* Bar chart table */
.bar-table { width: 100%; border-collapse: collapse; }
.bar-table tr { border-bottom: 1px solid #f3f4f6; }
.bar-table td { padding: 5px 4px; vertical-align: middle; }
.bar-label { font-size: 11px; color: #374151; width: 38%; overflow: hidden; white-space: nowrap; }
.bar-wrap  { width: 48%; padding: 0 8px; }
.bar-bg    { background: #f3f4f6; border-radius: 3px; height: 8px; }
.bar-fill  { background: #5B6EF5; border-radius: 3px; height: 8px; }
.bar-num   { font-size: 11px; color: #6b7280; text-align: right; width: 14%; white-space: nowrap; }

/* Device pills */
.device-row { display: table; width: 100%; border-spacing: 8px; border-collapse: separate; }
.device-cell { display: table-cell; background: #f8f9fc; border: 1px solid #e5e7eb; border-radius: 6px; padding: 10px 14px; text-align: center; }
.device-name  { font-size: 10px; color: #6b7280; text-transform: capitalize; }
.device-val   { font-size: 18px; font-weight: 700; color: #1a1a2e; }
.device-pct   { font-size: 10px; color: #9ca3af; }

.footer { border-top: 1px solid #e5e7eb; margin-top: 30px; padding-top: 8px; font-size: 10px; color: #9ca3af; text-align: center; }
</style>
</head>
<body>

{{-- Header --}}
<div class="page-header" style="display:table;width:100%">
    <div style="display:table-cell;vertical-align:bottom">
        <div class="site-name">{{ $site->domain }}</div>
        <div class="subtitle">Analytics Report &nbsp;·&nbsp; {{ $from->format('M j, Y') }} – {{ $to->format('M j, Y') }}</div>
    </div>
    <div style="display:table-cell;vertical-align:bottom;text-align:right">
        <div class="logo">Generated by Statalog<br>{{ now()->format('M j, Y') }}</div>
    </div>
</div>

{{-- Summary --}}
@if(in_array('summary', $sections) && isset($visitors))
<div class="section">
    <div class="section-title">Summary</div>
    @php
        $makeTrend = function($cur, $prev): array {
            if ($prev == 0) return $cur > 0 ? ['+100%', 'up'] : ['—', 'flat'];
            $pct = round((($cur - $prev) / $prev) * 100, 1);
            return [($pct >= 0 ? '+' : '') . $pct . '%', $pct > 0 ? 'up' : ($pct < 0 ? 'down' : 'flat')];
        };
        $statItems = [
            ['Visitors',     number_format($visitors),    ...$makeTrend($visitors, $prevVisitors)],
            ['Sessions',     number_format($sessions),    ...$makeTrend($sessions, $prevSessions)],
            ['Pageviews',    number_format($pageviews),   ...$makeTrend($pageviews, $prevPageviews)],
            ['Bounce rate',  round($bounceRate) . '%',    '', 'flat'],
            ['Avg duration', floor($avgDuration/60) . ':' . str_pad($avgDuration%60,2,'0',STR_PAD_LEFT), '', 'flat'],
        ];
    @endphp
    <div class="stats-grid">
        <div class="stats-row">
            @foreach($statItems as $s)
            <div class="stat-cell">
                <div class="stat-label">{{ $s[0] }}</div>
                <div class="stat-value">{{ $s[1] }}</div>
                @if($s[2])
                <div class="stat-trend trend-{{ $s[3] }}">{{ $s[2] }} vs prev period</div>
                @endif
            </div>
            @endforeach
        </div>
    </div>
</div>
@endif

{{-- Top Pages --}}
@if(in_array('pages', $sections) && !empty($topPages))
<div class="section">
    <div class="section-title">Top Pages</div>
    @php $maxPv = max(array_column($topPages, 'pageviews') ?: [1]); @endphp
    <table class="bar-table">
        @foreach($topPages as $p)
        <tr>
            <td class="bar-label">{{ $p['url'] }}</td>
            <td class="bar-wrap">
                <div class="bar-bg">
                    <div class="bar-fill" style="width:{{ min(100, round($p['pageviews']/$maxPv*100)) }}%"></div>
                </div>
            </td>
            <td class="bar-num">{{ number_format($p['pageviews']) }}</td>
        </tr>
        @endforeach
    </table>
</div>
@endif

{{-- Traffic Sources --}}
@if(in_array('sources', $sections) && !empty($sources))
<div class="section">
    <div class="section-title">Traffic Sources</div>
    @php $maxVisits = max(array_column($sources, 'visits') ?: [1]); @endphp
    <table class="bar-table">
        @foreach($sources as $s)
        <tr>
            <td class="bar-label">{{ $s['source'] }}</td>
            <td class="bar-wrap">
                <div class="bar-bg">
                    <div class="bar-fill" style="width:{{ min(100, round($s['visits']/$maxVisits*100)) }}%"></div>
                </div>
            </td>
            <td class="bar-num">{{ number_format($s['visits']) }}</td>
        </tr>
        @endforeach
    </table>
</div>
@endif

{{-- Locations --}}
@if(in_array('locations', $sections) && !empty($locations))
<div class="section">
    <div class="section-title">Locations</div>
    @php $maxLoc = max(array_column($locations, 'visitors') ?: [1]); @endphp
    <table class="bar-table">
        @foreach($locations as $l)
        <tr>
            <td class="bar-label">{{ $l['country'] ?: 'Unknown' }}</td>
            <td class="bar-wrap">
                <div class="bar-bg">
                    <div class="bar-fill" style="width:{{ min(100, round($l['visitors']/$maxLoc*100)) }}%"></div>
                </div>
            </td>
            <td class="bar-num">{{ number_format($l['visitors']) }}</td>
        </tr>
        @endforeach
    </table>
</div>
@endif

{{-- Devices & Browsers --}}
@if(in_array('devices', $sections) && !empty($devices))
<div class="section">
    <div class="section-title">Devices &amp; Browsers</div>
    @php
        $totalDeviceVisitors = array_sum(array_column($devices, 'visitors')) ?: 1;
    @endphp
    <div class="device-row" style="margin-bottom:12px">
        @foreach($devices as $d)
        <div class="device-cell">
            <div class="device-name">{{ ucfirst($d['device'] ?: 'Unknown') }}</div>
            <div class="device-val">{{ number_format($d['visitors']) }}</div>
            <div class="device-pct">{{ round($d['visitors']/$totalDeviceVisitors*100) }}%</div>
        </div>
        @endforeach
    </div>

    @if(!empty($browsers))
    @php $maxBr = max(array_column($browsers, 'visitors') ?: [1]); @endphp
    <table class="bar-table">
        @foreach($browsers as $b)
        <tr>
            <td class="bar-label">{{ $b['browser'] ?: 'Unknown' }}</td>
            <td class="bar-wrap">
                <div class="bar-bg">
                    <div class="bar-fill" style="width:{{ min(100, round($b['visitors']/$maxBr*100)) }}%"></div>
                </div>
            </td>
            <td class="bar-num">{{ number_format($b['visitors']) }}</td>
        </tr>
        @endforeach
    </table>
    @endif
</div>
@endif

<div class="footer">Statalog — Privacy-first analytics &nbsp;·&nbsp; statalog.com</div>

</body>
</html>
