<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Middleware;

use App\Contracts\ApiKeyContext;
use App\Contracts\ApiKeyValidator;
use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ApiAuthenticate
{
    public function __construct(private readonly ApiKeyValidator $validator) {}

    public function handle(Request $request, Closure $next): Response
    {
        $key = $this->extractKey($request);

        if ($key === '') {
            return response()->json(['error' => 'Missing API key. Pass via Authorization: Bearer or ?api_key=.'], 401);
        }

        $context = $this->validator->validate($key);

        if ($context === null) {
            return response()->json(['error' => 'Invalid or expired API key.'], 401);
        }

        // Bind the resolved context so controllers can scope data to the key owner.
        app()->instance(ApiKeyContext::class, $context);

        return $next($request);
    }

    private function extractKey(Request $request): string
    {
        $bearer = $request->bearerToken() ?? '';
        if ($bearer !== '') {
            return $bearer;
        }

        return trim($request->query('api_key', ''));
    }
}
