<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\User\Concerns\HasDateRange;
use App\Repositories\AnalyticsRepository;
use Illuminate\Http\Request;

class BotController extends Controller
{
    use HasDateRange;

    public function __construct(protected AnalyticsRepository $analytics) {}

    public function index(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        return view('user.bots.index', [
            'site'        => $site,
            'breadcrumbs' => [['label' => 'Bots']],
        ]);
    }

    public function data(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return response()->json([]);
        }

        if (!$site->track_bots) {
            return response()->json([
                'track_bots_disabled' => true,
            ]);
        }

        [$from, $to] = $this->getDateRange($request);
        $botsRepo   = $this->analytics->onlyBots();
        $humansRepo = $this->analytics; // default = humans only

        return response()->json([
            'totals' => [
                'bot_hits'   => $botsRepo->getTotalPageviews($site->site_id, $from, $to),
                'human_hits' => $humansRepo->getTotalPageviews($site->site_id, $from, $to),
            ],
            'by_bot'    => $botsRepo->getBotBreakdown($site->site_id, $from, $to),
            'over_time' => $botsRepo->getBotsOverTime($site->site_id, $from, $to, $site->timezone),
            'top_pages' => $botsRepo->getBotTopPages($site->site_id, $from, $to),
        ]);
    }
}
