<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\User\Concerns\HasDateRange;
use App\Repositories\AnalyticsRepository;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    use HasDateRange;

    public function __construct(protected AnalyticsRepository $analytics) {}

    public function index(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create')->with('warning', 'Please add a website first.');
        }

        return view('user.dashboard', [
            'site' => $site,
            'breadcrumbs' => [['label' => 'Dashboard']],
        ]);
    }

    public function hostnames(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return response()->json([]);
        }

        [$from, $to] = $this->getDateRange($request);

        return response()->json(
            $this->analyticsFor($site)->getDistinctHostnames($site->site_id, $from, $to)
        );
    }

    public function data(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return response()->json([]);
        }

        [$from, $to] = $this->getDateRange($request);
        [$prevFrom, $prevTo] = $this->getPreviousDateRange($from, $to);
        $repo = $this->analyticsFor($site, $request->input('hostname'));

        $visitors        = $repo->getUniqueVisitors($site->site_id, $from, $to);
        $prevVisitors    = $repo->getUniqueVisitors($site->site_id, $prevFrom, $prevTo);
        $sessions        = $repo->getTotalSessions($site->site_id, $from, $to);
        $prevSessions    = $repo->getTotalSessions($site->site_id, $prevFrom, $prevTo);
        $pageviews       = $repo->getTotalPageviews($site->site_id, $from, $to);
        $prevPageviews   = $repo->getTotalPageviews($site->site_id, $prevFrom, $prevTo);
        $bounceRate      = $repo->getBounceRate($site->site_id, $from, $to);
        $prevBounceRate  = $repo->getBounceRate($site->site_id, $prevFrom, $prevTo);
        $avgDuration     = $repo->getAvgVisitDuration($site->site_id, $from, $to);
        $prevAvgDuration = $repo->getAvgVisitDuration($site->site_id, $prevFrom, $prevTo);

        return response()->json([
            'stats' => [
                ['metric' => 'visitors',  'label' => 'Unique Visitors', 'value' => number_format($visitors),            'trend' => $this->calculateTrend($visitors, $prevVisitors),       'icon' => 'people'],
                ['metric' => 'sessions',  'label' => 'Total Sessions',  'value' => number_format($sessions),            'trend' => $this->calculateTrend($sessions, $prevSessions),       'icon' => 'cursor'],
                ['metric' => 'pageviews', 'label' => 'Total Pageviews', 'value' => number_format($pageviews),           'trend' => $this->calculateTrend($pageviews, $prevPageviews),     'icon' => 'eye'],
                ['metric' => 'bounce',    'label' => 'Bounce Rate',     'value' => $bounceRate . '%',                   'trend' => -$this->calculateTrend($bounceRate, $prevBounceRate),  'icon' => 'arrow-return-left'],
                ['metric' => 'duration',  'label' => 'Avg Duration',    'value' => $this->formatDuration($avgDuration), 'trend' => $this->calculateTrend($avgDuration, $prevAvgDuration), 'icon' => 'clock'],
            ],
            'topPages'    => $repo->getTopPages($site->site_id, $from, $to),
            'sources'     => $repo->getTrafficSources($site->site_id, $from, $to),
            'locations'   => $repo->getLocations($site->site_id, $from, $to),
            'mapPoints'   => $repo->getVisitorMapPoints($site->site_id, $from, $to),
            'devices'     => $repo->getDevices($site->site_id, $from, $to),
            'browsers'    => $repo->getBrowsers($site->site_id, $from, $to),
            'os'          => $repo->getOperatingSystems($site->site_id, $from, $to),
            'resolutions' => $repo->getScreenResolutions($site->site_id, $from, $to),
        ]);
    }

    public function chart(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return response()->json([]);
        }

        [$from, $to] = $this->getDateRange($request);

        return response()->json(
            $this->analyticsFor($site, $request->input('hostname'))->getVisitorsOverTime($site->site_id, $from, $to, $site->timezone)
        );
    }
}
