<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\User\Concerns\HasDateRange;
use App\Repositories\AnalyticsRepository;
use Illuminate\Http\Request;

class ErrorController extends Controller
{
    use HasDateRange;

    public function __construct(protected AnalyticsRepository $analytics) {}

    public function index(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        return view('user.errors.index', [
            'site'        => $site,
            'breadcrumbs' => [['label' => 'Errors']],
        ]);
    }

    public function data(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return response()->json([]);
        }

        [$from, $to] = $this->getDateRange($request);
        $repo = $this->analyticsFor($site);

        return response()->json([
            'stats'  => $repo->getErrorStats($site->site_id, $from, $to),
            'chart'  => $repo->getErrorsOverTime($site->site_id, $from, $to, $site->timezone),
            'groups' => $repo->getErrorGroups($site->site_id, $from, $to),
        ]);
    }

    public function show(Request $request, string $fingerprint)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        return view('user.errors.show', [
            'site'        => $site,
            'fingerprint' => $fingerprint,
            'breadcrumbs' => [
                ['label' => 'Errors', 'url' => route('user.errors')],
                ['label' => substr($fingerprint, 0, 8)],
            ],
        ]);
    }

    public function showData(Request $request, string $fingerprint)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return response()->json([]);
        }

        [$from, $to] = $this->getDateRange($request);

        return response()->json(
            $this->analyticsFor($site)->getErrorDetail($site->site_id, $fingerprint, $from, $to)
        );
    }
}
