<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\User\Concerns\HasDateRange;
use App\Models\Funnel;
use App\Repositories\AnalyticsRepository;
use Illuminate\Http\Request;

class FunnelController extends Controller
{
    use HasDateRange;

    public function __construct(protected AnalyticsRepository $analytics) {}

    public function index(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        $funnels = $site->funnels()->with('steps')->get();

        return view('user.funnels.index', [
            'site'        => $site,
            'funnels'     => $funnels,
            'breadcrumbs' => [['label' => 'Funnels']],
        ]);
    }

    public function create(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        return view('user.funnels.create', [
            'site' => $site,
            'breadcrumbs' => [
                ['label' => 'Funnels', 'url' => route('user.funnels.index')],
                ['label' => 'Create'],
            ],
        ]);
    }

    public function store(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        $validated = $request->validate([
            'name'          => 'required|string|max:255',
            'steps'         => 'required|array|min:2|max:10',
            'steps.*.label' => 'required|string|max:255',
            'steps.*.path'  => 'required|string|starts_with:/',
        ]);

        $funnel = $site->funnels()->create(['name' => $validated['name']]);

        foreach ($validated['steps'] as $i => $step) {
            $funnel->steps()->create([
                'label'      => $step['label'],
                'path'       => $step['path'],
                'step_order' => $i + 1,
            ]);
        }

        return redirect()->route('user.funnels.index')->with('success', 'Funnel created successfully.');
    }

    public function edit(Request $request, Funnel $funnel)
    {
        $site = $this->getCurrentSite($request);
        abort_if(!$site || $funnel->site_id !== $site->id, 403);

        $funnel->load('steps');

        return view('user.funnels.edit', [
            'site'   => $site,
            'funnel' => $funnel,
            'breadcrumbs' => [
                ['label' => 'Funnels', 'url' => route('user.funnels.index')],
                ['label' => 'Edit ' . $funnel->name],
            ],
        ]);
    }

    public function update(Request $request, Funnel $funnel)
    {
        $site = $this->getCurrentSite($request);
        abort_if(!$site || $funnel->site_id !== $site->id, 403);

        $validated = $request->validate([
            'name'          => 'required|string|max:255',
            'steps'         => 'required|array|min:2|max:10',
            'steps.*.label' => 'required|string|max:255',
            'steps.*.path'  => 'required|string|starts_with:/',
        ]);

        $funnel->update(['name' => $validated['name']]);
        $funnel->steps()->delete();

        foreach ($validated['steps'] as $i => $step) {
            $funnel->steps()->create([
                'label'      => $step['label'],
                'path'       => $step['path'],
                'step_order' => $i + 1,
            ]);
        }

        return redirect()->route('user.funnels.index')->with('success', 'Funnel updated successfully.');
    }

    public function destroy(Request $request, Funnel $funnel)
    {
        $site = $this->getCurrentSite($request);
        abort_if(!$site || $funnel->site_id !== $site->id, 403);

        $funnel->delete();

        return redirect()->route('user.funnels.index')->with('success', 'Funnel deleted successfully.');
    }

    public function report(Request $request, Funnel $funnel)
    {
        $site = $this->getCurrentSite($request);
        abort_if(!$site || $funnel->site_id !== $site->id, 403);

        $funnel->load('steps');
        [$from, $to] = $this->getDateRange($request);

        $stepPaths  = $funnel->steps->pluck('path')->toArray();
        $stepCounts = $this->analyticsFor($site, $request->input('hostname'))->getFunnelData($site->site_id, $stepPaths, $from, $to);

        $steps = [];
        foreach ($funnel->steps as $i => $step) {
            $count     = $stepCounts[$i] ?? 0;
            $prevCount = $i > 0 ? ($stepCounts[$i - 1] ?? 0) : $count;
            $dropoff   = $i > 0 ? max(0, $prevCount - $count) : 0;
            $convRate  = $prevCount > 0 ? round(($count / $prevCount) * 100, 1) : 0;

            $steps[] = [
                'label'           => $step->label,
                'path'            => $step->path,
                'visitors'        => $count,
                'dropoff'         => $dropoff,
                'conversion_rate' => $convRate,
            ];
        }

        $overallRate = 0;
        if (count($stepCounts) >= 2 && $stepCounts[0] > 0) {
            $overallRate = round((end($stepCounts) / $stepCounts[0]) * 100, 1);
        }

        return view('user.funnels.report', [
            'site'        => $site,
            'funnel'      => $funnel,
            'steps'       => $steps,
            'overallRate' => $overallRate,
            'breadcrumbs' => [
                ['label' => 'Funnels', 'url' => route('user.funnels.index')],
                ['label' => $funnel->name],
            ],
        ]);
    }
}
