<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\User\Concerns\HasDateRange;
use App\Models\Goal;
use App\Models\GoalCompletion;
use App\Repositories\AnalyticsRepository;
use Illuminate\Http\Request;

class GoalController extends Controller
{
    use HasDateRange;

    public function __construct(protected AnalyticsRepository $analytics) {}

    public function index(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        $goals = $site->goals()->get();
        [$from, $to] = $this->getDateRange($request);

        $goalsData = $goals->map(function ($goal) use ($from, $to) {
            $completions = GoalCompletion::where('goal_id', $goal->id)
                ->whereBetween('created_at', [$from, $to])
                ->count();
            return [
                'id'          => $goal->id,
                'name'        => $goal->name,
                'target_path' => $goal->target_path,
                'match_type'  => $goal->match_type,
                'completions' => $completions,
            ];
        });

        return view('user.goals.index', [
            'site'        => $site,
            'goals'       => $goalsData,
            'breadcrumbs' => [['label' => 'Goals']],
        ]);
    }

    public function create(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        return view('user.goals.create', [
            'site' => $site,
            'breadcrumbs' => [
                ['label' => 'Goals', 'url' => route('user.goals.index')],
                ['label' => 'Create'],
            ],
        ]);
    }

    public function store(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        $validated = $request->validate([
            'name'           => 'required|string|max:255',
            'match_type'     => 'required|in:exact,starts_with,contains',
            'target_path'    => 'required|string|starts_with:/',
            'monetary_value' => 'nullable|numeric|min:0',
        ]);

        $site->goals()->create($validated);

        return redirect()->route('user.goals.index')->with('success', 'Goal created successfully.');
    }

    public function edit(Request $request, Goal $goal)
    {
        $site = $this->getCurrentSite($request);
        abort_if(!$site || $goal->site_id !== $site->id, 403);

        return view('user.goals.edit', [
            'site' => $site,
            'goal' => $goal,
            'breadcrumbs' => [
                ['label' => 'Goals', 'url' => route('user.goals.index')],
                ['label' => 'Edit ' . $goal->name],
            ],
        ]);
    }

    public function update(Request $request, Goal $goal)
    {
        $site = $this->getCurrentSite($request);
        abort_if(!$site || $goal->site_id !== $site->id, 403);

        $validated = $request->validate([
            'name'           => 'required|string|max:255',
            'match_type'     => 'required|in:exact,starts_with,contains',
            'target_path'    => 'required|string|starts_with:/',
            'monetary_value' => 'nullable|numeric|min:0',
        ]);

        $goal->update($validated);

        return redirect()->route('user.goals.index')->with('success', 'Goal updated successfully.');
    }

    public function destroy(Request $request, Goal $goal)
    {
        $site = $this->getCurrentSite($request);
        abort_if(!$site || $goal->site_id !== $site->id, 403);

        $goal->delete();

        return redirect()->route('user.goals.index')->with('success', 'Goal deleted successfully.');
    }

    public function report(Request $request, Goal $goal)
    {
        $site = $this->getCurrentSite($request);
        abort_if(!$site || $goal->site_id !== $site->id, 403);

        return view('user.goals.report', [
            'site' => $site,
            'goal' => $goal,
            'breadcrumbs' => [
                ['label' => 'Goals', 'url' => route('user.goals.index')],
                ['label' => $goal->name],
            ],
        ]);
    }

    public function reportData(Request $request, Goal $goal)
    {
        $site = $this->getCurrentSite($request);
        abort_if(!$site || $goal->site_id !== $site->id, 403);

        [$from, $to] = $this->getDateRange($request);

        $completions = GoalCompletion::where('goal_id', $goal->id)
            ->whereBetween('created_at', [$from, $to])
            ->selectRaw('DATE(created_at) as date, count(*) as completions')
            ->groupBy('date')
            ->orderBy('date')
            ->get();

        return response()->json([
            'chart' => $completions,
            'total' => $completions->sum('completions'),
        ]);
    }
}
