<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\User\Concerns\HasDateRange;
use App\Repositories\AnalyticsRepository;
use App\Services\SettingsService;
use Illuminate\Http\Request;

class LiveStatsController extends Controller
{
    use HasDateRange;

    public function __construct(protected AnalyticsRepository $analytics) {}

    public function index(Request $request, SettingsService $settings)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        return view('user.live', [
            'site'        => $site,
            'hideCities'  => (bool) $settings->get('hide_cities', false),
            'breadcrumbs' => [['label' => 'Live Stats']],
        ]);
    }

    public function data(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return response()->json([]);
        }

        $hostname = $request->input('hostname') ?: null;
        $minutes  = (int) $request->input('minutes', 30);
        $minutes  = max(5, min(60, $minutes));
        $repo = $this->analyticsFor($site);

        $response = [
            'count30' => $repo->getLiveVisitorCount($site->site_id, 30, $hostname),
            'count60' => $repo->getLiveVisitorCount($site->site_id, 60, $hostname),
            'chart'   => $repo->getLiveVisitors($site->site_id, 60, $hostname),
            'recent'  => $repo->getRecentVisits($site->site_id, 60, $hostname, $minutes),
        ];

        if ($site->track_subdomains) {
            $rows = $repo->getLiveSubdomains($site->site_id);
            $response['subdomains'] = array_column($rows, 'hostname');
        }

        return response()->json($response);
    }
}
