<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\User\Concerns\HasDateRange;
use App\Repositories\AnalyticsRepository;
use Illuminate\Http\Request;

class OverviewController extends Controller
{
    use HasDateRange;

    public function __construct(protected AnalyticsRepository $analytics) {}

    public function index(Request $request)
    {
        $user = $request->user();
        $sites = $user->sites()->get();

        if ($sites->isEmpty()) {
            return redirect()->route('user.sites.create');
        }

        if ($sites->count() === 1) {
            return redirect()->route('user.dashboard');
        }

        [$from, $to] = $this->getDateRange($request);
        [$prevFrom, $prevTo] = $this->getPreviousDateRange($from, $to);

        $siteStats         = [];
        $totalVisitors     = 0;
        $totalSessions     = 0;
        $totalPageviews    = 0;
        $prevTotalVisitors = 0;

        foreach ($sites as $site) {
            $repo = $this->analyticsFor($site);

            $visitors     = $repo->getUniqueVisitors($site->site_id, $from, $to);
            $sessions     = $repo->getTotalSessions($site->site_id, $from, $to);
            $pageviews    = $repo->getTotalPageviews($site->site_id, $from, $to);
            $prevVisitors = $repo->getUniqueVisitors($site->site_id, $prevFrom, $prevTo);

            $totalVisitors     += $visitors;
            $totalSessions     += $sessions;
            $totalPageviews    += $pageviews;
            $prevTotalVisitors += $prevVisitors;

            $siteStats[] = [
                'site'      => $site,
                'visitors'  => $visitors,
                'sessions'  => $sessions,
                'pageviews' => $pageviews,
                'trend'     => $this->calculateTrend($visitors, $prevVisitors),
            ];
        }

        usort($siteStats, fn ($a, $b) => $b['visitors'] - $a['visitors']);

        return view('user.overview', [
            'siteStats'      => $siteStats,
            'totalVisitors'  => $totalVisitors,
            'totalSessions'  => $totalSessions,
            'totalPageviews' => $totalPageviews,
            'totalTrend'     => $this->calculateTrend($totalVisitors, $prevTotalVisitors),
            'breadcrumbs'    => [['label' => 'All Sites']],
        ]);
    }
}
