<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\User\Concerns\HasDateRange;
use App\Repositories\AnalyticsRepository;
use Barryvdh\DomPDF\Facade\Pdf;
use Carbon\Carbon;
use Illuminate\Http\Request;

class PdfReportController extends Controller
{
    use HasDateRange;

    public function __construct(protected AnalyticsRepository $analytics) {}

    public function index(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        return view('user.pdf-report', [
            'site'        => $site,
            'breadcrumbs' => [['label' => 'PDF Report']],
        ]);
    }

    public function generate(Request $request)
    {
        $site = $this->getCurrentSite($request);
        if (!$site) {
            return redirect()->route('user.sites.create');
        }

        [$from, $to] = $this->getDateRange($request);
        [$prevFrom, $prevTo] = $this->getPreviousDateRange($from, $to);

        $sections = $request->input('sections', ['summary', 'pages', 'sources', 'locations', 'devices']);
        $repo = $this->analyticsFor($site);

        $data = [];

        if (in_array('summary', $sections)) {
            $data['visitors']      = $repo->getUniqueVisitors($site->site_id, $from, $to);
            $data['prevVisitors']  = $repo->getUniqueVisitors($site->site_id, $prevFrom, $prevTo);
            $data['sessions']      = $repo->getTotalSessions($site->site_id, $from, $to);
            $data['prevSessions']  = $repo->getTotalSessions($site->site_id, $prevFrom, $prevTo);
            $data['pageviews']     = $repo->getTotalPageviews($site->site_id, $from, $to);
            $data['prevPageviews'] = $repo->getTotalPageviews($site->site_id, $prevFrom, $prevTo);
            $data['bounceRate']    = $repo->getBounceRate($site->site_id, $from, $to);
            $data['avgDuration']   = $repo->getAvgVisitDuration($site->site_id, $from, $to);
        }

        if (in_array('pages', $sections)) {
            $data['topPages'] = $repo->getTopPages($site->site_id, $from, $to, 15);
        }

        if (in_array('sources', $sections)) {
            $data['sources'] = $repo->getTrafficSources($site->site_id, $from, $to, 15);
        }

        if (in_array('locations', $sections)) {
            $data['locations'] = $repo->getLocations($site->site_id, $from, $to, 15);
        }

        if (in_array('devices', $sections)) {
            $data['devices']  = $repo->getDevices($site->site_id, $from, $to);
            $data['browsers'] = $repo->getBrowsers($site->site_id, $from, $to, 10);
        }

        $fromDate = Carbon::parse($from);
        $toDate   = Carbon::parse($to);

        $pdf = Pdf::loadView('user.pdf.report', array_merge($data, [
            'site'     => $site,
            'from'     => $fromDate,
            'to'       => $toDate,
            'sections' => $sections,
        ]))->setPaper('a4');

        $filename = 'analytics-' . $site->domain . '-' . $fromDate->format('Y-m-d') . '.pdf';

        return $pdf->download($filename);
    }
}
