<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Services\SettingsService;
use Illuminate\Http\Request;

class SettingsController extends Controller
{
    public function __construct(protected SettingsService $settings) {}

    public function index(Request $request)
    {
        return view('user.general', [
            'user'         => $request->user(),
            'settings'     => $this->settings->all(),
            'excludedIps'  => $this->settings->get('excluded_ips', ''),
            'hideCities'   => (bool) $this->settings->get('hide_cities', false),
            'breadcrumbs'  => [['label' => 'General']],
        ]);
    }

    public function update(Request $request)
    {
        $raw = $request->input('excluded_ips', '');

        $ips = array_values(array_filter(
            array_map('trim', preg_split('/[\s,]+/', $raw) ?: []),
            fn ($ip) => $ip !== '' && filter_var($ip, FILTER_VALIDATE_IP)
        ));

        $this->settings->set('excluded_ips', implode(',', $ips), 'privacy');
        $this->settings->set('hide_cities', $request->boolean('hide_cities') ? '1' : '0', 'privacy');

        return redirect()->route('user.general')->with('success', 'Settings saved.');
    }
}
