<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Site;
use App\Repositories\AnalyticsRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class SiteController extends Controller
{
    public function __construct(protected AnalyticsRepository $analytics) {}

    public function index()
    {
        $sites     = auth()->user()->sites;
        $siteIds   = $sites->pluck('site_id')->toArray();
        $hitCounts = $this->analytics->getSiteHitCounts($siteIds);

        return view('user.sites.index', [
            'breadcrumbs'    => [['label' => 'Websites']],
            'sites'          => $sites,
            'hitCounts'      => $hitCounts,
            'todayTotal'     => array_sum(array_column($hitCounts, 'today')),
            'thisMonthTotal' => array_sum(array_column($hitCounts, 'this_month')),
            'lastMonthTotal' => array_sum(array_column($hitCounts, 'last_month')),
        ]);
    }

    public function create()
    {
        return view('user.sites.create', [
            'breadcrumbs' => [
                ['label' => 'Websites', 'url' => route('user.sites.index')],
                ['label' => 'Add Website'],
            ],
        ]);
    }

    private function cleanDomain(string $domain): string
    {
        $domain = trim($domain);
        $domain = preg_replace('#^https?://#i', '', $domain);
        $domain = rtrim($domain, '/');
        return strtolower($domain);
    }

    public function store(Request $request)
    {
        $request->merge(['domain' => $this->cleanDomain($request->input('domain', ''))]);

        $request->validate([
            'name'     => ['required', 'string', 'max:255'],
            'domain'   => ['required', 'string', 'max:255', 'regex:/^([a-z0-9-]+\.)+[a-z]{2,}$/i'],
            'timezone' => ['required', 'string', 'timezone'],
        ], [
            'domain.regex' => 'Please enter a valid domain name (e.g. example.com).',
        ]);

        $site = Site::create([
            'name'             => $request->input('name'),
            'domain'           => $request->input('domain'),
            'timezone'         => $request->input('timezone'),
            'track_subdomains' => $request->boolean('track_subdomains'),
            'track_bots'       => $request->boolean('track_bots'),
        ]);

        session(['current_site_id' => $site->site_id]);

        return redirect()->route('user.sites.show', $site)->with('success', 'Website added. Copy the tracking script below.');
    }

    public function show(Site $site)
    {
        abort_unless($site->user_id === auth()->id(), 403);

        return view('user.sites.show', [
            'breadcrumbs' => [
                ['label' => 'Websites', 'url' => route('user.sites.index')],
                ['label' => $site->name],
            ],
            'site' => $site,
        ]);
    }

    public function update(Request $request, Site $site)
    {
        abort_unless($site->user_id === auth()->id(), 403);

        $request->merge(['domain' => $this->cleanDomain($request->input('domain', ''))]);

        $request->validate([
            'name'     => ['required', 'string', 'max:255'],
            'domain'   => ['required', 'string', 'max:255', 'regex:/^([a-z0-9-]+\.)+[a-z]{2,}$/i'],
            'timezone' => ['required', 'string', 'timezone'],
        ], [
            'domain.regex' => 'Please enter a valid domain name (e.g. example.com).',
        ]);

        $updates = [
            'name'             => $request->input('name'),
            'domain'           => $request->input('domain'),
            'timezone'         => $request->input('timezone'),
            'track_subdomains' => $request->boolean('track_subdomains'),
            'track_bots'       => $request->boolean('track_bots'),
        ];

        $isPublic = $request->boolean('is_public');
        $updates['is_public'] = $isPublic;

        if ($isPublic && !$site->public_token) {
            $updates['public_token'] = Str::random(48);
        }

        $passwordProtected = $request->boolean('password_protected');
        if (!$passwordProtected) {
            $updates['public_password'] = null;
        } else {
            $newPassword = trim($request->input('public_password', ''));
            if ($newPassword !== '') {
                $updates['public_password'] = Hash::make($newPassword);
            }
        }

        $sections = $request->input('public_sections', []);
        $updates['public_sections'] = !empty($sections) ? $sections : null;

        $site->update($updates);

        return back()->with('success', 'Website updated.');
    }

    public function destroy(Site $site)
    {
        abort_unless($site->user_id === auth()->id(), 403);

        $site->delete();

        return redirect()->route('user.sites.index')->with('success', 'Website removed.');
    }
}
