<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Controllers\User\Concerns\HasDateRange;
use Illuminate\Validation\Rule;
use App\Models\Site;
use App\Repositories\AnalyticsRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class SiteController extends Controller
{
    use HasDateRange;

    public function __construct(protected AnalyticsRepository $analytics) {}

    public function index(Request $request)
    {
        $sites = $request->user()->sites()->get();

        [$from, $to]         = $this->getDateRange($request);
        [$prevFrom, $prevTo] = $this->getPreviousDateRange($from, $to);

        $siteStats         = [];
        $totalVisitors     = 0;
        $totalSessions     = 0;
        $totalPageviews    = 0;
        $prevTotalVisitors = 0;

        foreach ($sites as $site) {
            $repo = $this->analyticsFor($site);

            $visitors     = $repo->getUniqueVisitors($site->site_id, $from, $to);
            $sessions     = $repo->getTotalSessions($site->site_id, $from, $to);
            $pageviews    = $repo->getTotalPageviews($site->site_id, $from, $to);
            $prevVisitors = $repo->getUniqueVisitors($site->site_id, $prevFrom, $prevTo);

            $totalVisitors     += $visitors;
            $totalSessions     += $sessions;
            $totalPageviews    += $pageviews;
            $prevTotalVisitors += $prevVisitors;

            $siteStats[] = [
                'site'      => $site,
                'visitors'  => $visitors,
                'sessions'  => $sessions,
                'pageviews' => $pageviews,
                'trend'     => $this->calculateTrend($visitors, $prevVisitors),
            ];
        }

        usort($siteStats, fn ($a, $b) => $b['visitors'] - $a['visitors']);

        $billingUsage = null;
        if (class_exists(\Statalog\Cloud\Services\UsageService::class)) {
            $billingUsage = app(\Statalog\Cloud\Services\UsageService::class)
                ->currentPeriodUsage($request->user());
        }

        return view('user.sites.index', [
            'breadcrumbs'    => [['label' => 'Websites']],
            'sites'          => $sites,
            'siteStats'      => $siteStats,
            'totalVisitors'  => $totalVisitors,
            'totalSessions'  => $totalSessions,
            'totalPageviews' => $totalPageviews,
            'totalTrend'     => $this->calculateTrend($totalVisitors, $prevTotalVisitors),
            'billingUsage'   => $billingUsage,
        ]);
    }

    public function create()
    {
        return view('user.sites.create', [
            'breadcrumbs' => [
                ['label' => 'Websites', 'url' => route('user.sites.index')],
                ['label' => 'Add Website'],
            ],
        ]);
    }

    private function cleanDomain(string $domain): string
    {
        $domain = trim($domain);
        $domain = preg_replace('#^https?://#i', '', $domain);
        $domain = rtrim($domain, '/');
        return strtolower($domain);
    }

    public function store(Request $request)
    {
        $request->merge(['domain' => $this->cleanDomain($request->input('domain', ''))]);

        $request->validate([
            'name'     => ['required', 'string', 'max:255'],
            'domain'   => [
                'required', 'string', 'max:255',
                'regex:/^([a-z0-9-]+\.)+[a-z]{2,}$/i',
                Rule::unique('sites', 'domain')->where(fn ($q) => $q->where('user_id', auth()->id())->whereNull('deleted_at')),
            ],
            'timezone' => ['required', 'string', 'timezone'],
        ], [
            'domain.regex'  => 'Please enter a valid domain name (e.g. example.com).',
            'domain.unique' => 'You already have a website with this domain.',
        ]);

        $site = Site::create([
            'name'             => $request->input('name'),
            'domain'           => $request->input('domain'),
            'timezone'         => $request->input('timezone'),
            'track_subdomains' => $request->boolean('track_subdomains'),
            'track_bots'       => true,
        ]);

        session(['current_site_id' => $site->site_id]);

        return redirect()->route('user.sites.show', $site)->with('success', 'Website added. Copy the tracking script below.');
    }

    public function show(Site $site)
    {
        abort_unless($site->user_id === auth()->id(), 403);

        return view('user.sites.show', [
            'breadcrumbs' => [
                ['label' => 'Websites', 'url' => route('user.sites.index')],
                ['label' => $site->name],
            ],
            'site' => $site,
        ]);
    }

    public function update(Request $request, Site $site)
    {
        abort_unless($site->user_id === auth()->id(), 403);

        $request->merge(['domain' => $this->cleanDomain($request->input('domain', ''))]);

        $request->validate([
            'name'     => ['required', 'string', 'max:255'],
            'domain'   => [
                'required', 'string', 'max:255',
                'regex:/^([a-z0-9-]+\.)+[a-z]{2,}$/i',
                Rule::unique('sites', 'domain')
                    ->ignore($site->id)
                    ->where(fn ($q) => $q->where('user_id', auth()->id())->whereNull('deleted_at')),
            ],
            'timezone' => ['required', 'string', 'timezone'],
        ], [
            'domain.regex'  => 'Please enter a valid domain name (e.g. example.com).',
            'domain.unique' => 'You already have a website with this domain.',
        ]);

        $updates = [
            'name'             => $request->input('name'),
            'domain'           => $request->input('domain'),
            'timezone'         => $request->input('timezone'),
            'track_subdomains' => $request->boolean('track_subdomains'),
            'track_bots'       => true,
        ];

        $isPublic = $request->boolean('is_public');
        $updates['is_public'] = $isPublic;

        if ($isPublic) {
            if (empty($site->public_token)) {
                $updates['public_token'] = bin2hex(random_bytes(16));
            }
            $password = trim((string) $request->input('public_password', ''));
            if ($password !== '') {
                $updates['public_password'] = Hash::make($password);
            } elseif ($request->boolean('clear_public_password')) {
                $updates['public_password'] = null;
            }
            $sections = $request->input('public_sections', []);
            if (is_array($sections)) {
                $updates['public_sections'] = array_values(array_intersect(
                    $sections,
                    ['chart', 'top_pages', 'sources', 'countries', 'devices', 'browsers']
                ));
            }
        }

        $site->update($updates);

        return back()->with('success', 'Website updated.');
    }

    public function destroy(Request $request, Site $site)
    {
        abort_unless($site->user_id === auth()->id(), 403);

        $request->validate(
            ['password' => ['required', 'current_password']],
            ['password.current_password' => 'Incorrect password.']
        );

        // Purge ClickHouse data first (pageviews, events, errors).
        $this->analytics->deleteAllForSite($site->site_id);

        // Purge cloud-only stats (heatmap_events) if cloud is installed.
        if (class_exists(\Statalog\Cloud\Repositories\HeatmapRepository::class)) {
            app(\Statalog\Cloud\Repositories\HeatmapRepository::class)->deleteAllForSite($site->site_id);
        }

        $site->delete();

        return redirect()->route('user.sites.index')->with('success', 'Website and all its stats removed.');
    }
}
