<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Models\Site;
use App\Repositories\AnalyticsRepository;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class StatsController extends Controller
{
    public function __construct(private readonly AnalyticsRepository $analytics) {}

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private function resolveSite(Request $request): Site|JsonResponse
    {
        $siteId = trim($request->query('site_id', ''));
        if ($siteId === '') {
            return response()->json(['error' => 'site_id is required.'], 422);
        }

        $site = Site::where('site_id', $siteId)->first();
        if (!$site) {
            return response()->json(['error' => 'Site not found.'], 404);
        }

        return $site;
    }

    private function dateRange(Request $request): array
    {
        $from = $request->query('from', now()->subDays(30)->format('Y-m-d') . ' 00:00:00');
        $to   = $request->query('to',   now()->format('Y-m-d') . ' 23:59:59');

        // Accept bare dates (Y-m-d) and append time
        if (strlen($from) === 10) $from .= ' 00:00:00';
        if (strlen($to)   === 10) $to   .= ' 23:59:59';

        return [$from, $to];
    }

    private function limit(Request $request, int $default = 50, int $max = 500): int
    {
        return min((int) $request->query('limit', $default), $max);
    }

    // -------------------------------------------------------------------------
    // Endpoints
    // -------------------------------------------------------------------------

    /**
     * GET /api/v1/stats
     * Summary metrics: visitors, pageviews, sessions, bounce_rate, avg_duration.
     */
    public function summary(Request $request): JsonResponse
    {
        $site = $this->resolveSite($request);
        if ($site instanceof JsonResponse) return $site;

        [$from, $to] = $this->dateRange($request);
        $id = $site->site_id;

        return response()->json([
            'site_id'      => $id,
            'from'         => $from,
            'to'           => $to,
            'visitors'     => $this->analytics->getUniqueVisitors($id, $from, $to),
            'pageviews'    => $this->analytics->getTotalPageviews($id, $from, $to),
            'sessions'     => $this->analytics->getTotalSessions($id, $from, $to),
            'bounce_rate'  => round($this->analytics->getBounceRate($id, $from, $to), 2),
            'avg_duration' => $this->analytics->getAvgVisitDuration($id, $from, $to),
        ]);
    }

    /**
     * GET /api/v1/stats/timeseries
     * Visitors and pageviews grouped by day.
     */
    public function timeseries(Request $request): JsonResponse
    {
        $site = $this->resolveSite($request);
        if ($site instanceof JsonResponse) return $site;

        [$from, $to] = $this->dateRange($request);
        $tz = $request->query('timezone', $site->timezone ?? 'UTC');

        return response()->json([
            'site_id' => $site->site_id,
            'from'    => $from,
            'to'      => $to,
            'data'    => $this->analytics->getVisitorsOverTime($site->site_id, $from, $to, $tz),
        ]);
    }

    /**
     * GET /api/v1/pages
     * Top pages by pageviews.
     */
    public function pages(Request $request): JsonResponse
    {
        $site = $this->resolveSite($request);
        if ($site instanceof JsonResponse) return $site;

        [$from, $to] = $this->dateRange($request);

        return response()->json([
            'site_id' => $site->site_id,
            'from'    => $from,
            'to'      => $to,
            'data'    => $this->analytics->getPageBreakdown($site->site_id, $from, $to, $this->limit($request)),
        ]);
    }

    /**
     * GET /api/v1/referrers
     * Top referrer domains with visitors, sessions, and bounce rate.
     */
    public function referrers(Request $request): JsonResponse
    {
        $site = $this->resolveSite($request);
        if ($site instanceof JsonResponse) return $site;

        [$from, $to] = $this->dateRange($request);

        return response()->json([
            'site_id' => $site->site_id,
            'from'    => $from,
            'to'      => $to,
            'data'    => $this->analytics->getReferrerDomainStats($site->site_id, $from, $to),
        ]);
    }

    /**
     * GET /api/v1/channels
     * Traffic by channel (Organic, Direct, Referral, Social, Email, Paid, AI).
     */
    public function channels(Request $request): JsonResponse
    {
        $site = $this->resolveSite($request);
        if ($site instanceof JsonResponse) return $site;

        [$from, $to] = $this->dateRange($request);

        return response()->json([
            'site_id' => $site->site_id,
            'from'    => $from,
            'to'      => $to,
            'data'    => $this->analytics->getTrafficSources($site->site_id, $from, $to, $this->limit($request)),
        ]);
    }

    /**
     * GET /api/v1/locations
     * Visitors by country.
     */
    public function locations(Request $request): JsonResponse
    {
        $site = $this->resolveSite($request);
        if ($site instanceof JsonResponse) return $site;

        [$from, $to] = $this->dateRange($request);

        return response()->json([
            'site_id' => $site->site_id,
            'from'    => $from,
            'to'      => $to,
            'data'    => $this->analytics->getLocationsFull($site->site_id, $from, $to, $this->limit($request)),
        ]);
    }

    /**
     * GET /api/v1/devices
     * Visitors split by device type, browser, and OS.
     */
    public function devices(Request $request): JsonResponse
    {
        $site = $this->resolveSite($request);
        if ($site instanceof JsonResponse) return $site;

        [$from, $to] = $this->dateRange($request);
        $id = $site->site_id;

        return response()->json([
            'site_id'  => $id,
            'from'     => $from,
            'to'       => $to,
            'devices'  => $this->analytics->getDevices($id, $from, $to),
            'browsers' => $this->analytics->getBrowsers($id, $from, $to, $this->limit($request, 10)),
            'os'       => $this->analytics->getOperatingSystems($id, $from, $to, $this->limit($request, 10)),
        ]);
    }

    /**
     * GET /api/v1/events
     * Custom events with counts and properties breakdown.
     */
    public function events(Request $request): JsonResponse
    {
        $site = $this->resolveSite($request);
        if ($site instanceof JsonResponse) return $site;

        [$from, $to] = $this->dateRange($request);

        return response()->json([
            'site_id' => $site->site_id,
            'from'    => $from,
            'to'      => $to,
            'data'    => $this->analytics->getCustomEvents($site->site_id, $from, $to),
        ]);
    }

    /**
     * GET /api/v1/campaigns
     * UTM campaign stats.
     */
    public function campaigns(Request $request): JsonResponse
    {
        $site = $this->resolveSite($request);
        if ($site instanceof JsonResponse) return $site;

        [$from, $to] = $this->dateRange($request);

        return response()->json([
            'site_id' => $site->site_id,
            'from'    => $from,
            'to'      => $to,
            'data'    => $this->analytics->getCampaigns($site->site_id, $from, $to),
        ]);
    }

    /**
     * GET /api/v1/live
     * Visitors active in the last 30 minutes.
     */
    public function live(Request $request): JsonResponse
    {
        $site = $this->resolveSite($request);
        if ($site instanceof JsonResponse) return $site;

        $minutes = min((int) $request->query('minutes', 30), 60);

        return response()->json([
            'site_id'  => $site->site_id,
            'minutes'  => $minutes,
            'visitors' => $this->analytics->getLiveVisitorCount($site->site_id, $minutes),
        ]);
    }
}
