<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\User\Concerns;

use App\Models\Site;
use App\Repositories\AnalyticsRepository;
use Carbon\Carbon;
use Illuminate\Http\Request;

trait HasDateRange
{
    protected function getDateRange(Request $request): array
    {
        if ($request->filled('from') && $request->filled('to')) {
            return [
                Carbon::parse($request->from)->startOfDay()->toDateTimeString(),
                Carbon::parse($request->to)->endOfDay()->toDateTimeString(),
            ];
        }

        $range = $request->input('range', 'last7days');

        return match ($range) {
            'live' => [now()->subMinutes(30)->toDateTimeString(), now()->toDateTimeString()],
            'today' => [now()->startOfDay()->toDateTimeString(), now()->endOfDay()->toDateTimeString()],
            'yesterday' => [now()->subDay()->startOfDay()->toDateTimeString(), now()->subDay()->endOfDay()->toDateTimeString()],
            'last24h' => [now()->subHours(24)->toDateTimeString(), now()->toDateTimeString()],
            'last30days' => [now()->subDays(30)->startOfDay()->toDateTimeString(), now()->endOfDay()->toDateTimeString()],
            'this_month' => [now()->startOfMonth()->toDateTimeString(), now()->endOfDay()->toDateTimeString()],
            'last_month' => [now()->subMonth()->startOfMonth()->toDateTimeString(), now()->subMonth()->endOfMonth()->endOfDay()->toDateTimeString()],
            default => [now()->subDays(7)->startOfDay()->toDateTimeString(), now()->endOfDay()->toDateTimeString()],
        };
    }

    protected function getPreviousDateRange(string $from, string $to): array
    {
        $fromDate = Carbon::parse($from);
        $toDate = Carbon::parse($to);
        $diff = $fromDate->diffInDays($toDate);

        return [
            $fromDate->copy()->subDays($diff + 1)->toDateTimeString(),
            $fromDate->copy()->subDay()->endOfDay()->toDateTimeString(),
        ];
    }

    protected function getCurrentSite(Request $request)
    {
        $user = $request->user();

        if ($request->has('switch_site')) {
            session(['current_site_id' => $request->input('switch_site')]);
        }

        $currentSiteId = session('current_site_id');

        if ($currentSiteId) {
            $site = $user->sites()->where('site_id', $currentSiteId)->first();
            if ($site) {
                return $site;
            }
        }

        $site = $user->sites()->first();
        if ($site) {
            session(['current_site_id' => $site->site_id]);
        }

        return $site;
    }

    protected function formatDuration(int $seconds): string
    {
        $minutes = floor($seconds / 60);
        $secs = $seconds % 60;
        return sprintf('%d:%02d', $minutes, $secs);
    }

    protected function calculateTrend($current, $previous): float
    {
        if ($previous == 0) {
            return $current > 0 ? 100 : 0;
        }
        return round((($current - $previous) / $previous) * 100, 1);
    }

    protected function analyticsFor(Site $site, ?string $hostname = null): AnalyticsRepository
    {
        /** @var AnalyticsRepository $repo */
        $repo = $this->analytics;
        if (!($site->track_subdomains ?? true)) {
            $repo = $repo->withoutSubdomains($site->domain);
        }
        if ($hostname) {
            $repo = $repo->forHostname($hostname);
        }

        // Bot visibility — opt-in via ?bots=1 (include) or ?bots=only (bots only).
        // Only meaningful when the site has track_bots enabled; harmless otherwise.
        $botsParam = request()->input('bots');
        if ($botsParam === 'only') {
            $repo = $repo->onlyBots();
        } elseif ($botsParam === '1' || $botsParam === 'include') {
            $repo = $repo->includeBots();
        }

        return $repo;
    }
}
