<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Traits;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

trait BelongsToUser
{
    public static function bootBelongsToUser(): void
    {
        static::addGlobalScope('user', function (Builder $builder) {
            $userId = static::resolveUserId();
            if ($userId) {
                $builder->where($builder->getModel()->getTable() . '.user_id', $userId);
            }
        });

        static::creating(function (Model $model) {
            if (empty($model->user_id)) {
                $model->user_id = static::resolveUserId();
            }
        });
    }

    protected static function resolveUserId(): ?int
    {
        return auth()->id();
    }

    public static function withoutUserScope(): Builder
    {
        return static::withoutGlobalScope('user');
    }

    public function scopeForUser(Builder $query, int $userId): Builder
    {
        return $query->withoutGlobalScope('user')->where('user_id', $userId);
    }
}
