<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers;

use App\Models\Site;
use App\Repositories\AnalyticsRepository;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class PublicDashboardController extends Controller
{
    const ALL_SECTIONS = ['chart', 'pages', 'sources', 'locations', 'devices', 'browsers', 'os', 'resolutions'];

    public function __construct(protected AnalyticsRepository $analytics) {}

    public function show(string $token, Request $request)
    {
        $site = $this->findPublicSite($token);

        if ($site->public_password && !session('pub_unlocked_' . $token)) {
            return view('public.password', compact('site', 'token'));
        }

        $sections = $site->public_sections ?: self::ALL_SECTIONS;

        return view('public.dashboard', compact('site', 'token', 'sections'));
    }

    public function unlock(string $token, Request $request)
    {
        $site = $this->findPublicSite($token);

        if ($site->public_password && Hash::check($request->input('password', ''), $site->public_password)) {
            session(['pub_unlocked_' . $token => true]);
            return redirect()->route('public.dashboard', $token);
        }

        return back()->withErrors(['password' => 'Incorrect password.']);
    }

    public function data(string $token, Request $request)
    {
        $site = $this->findPublicSite($token);

        if ($site->public_password && !session('pub_unlocked_' . $token)) {
            return response()->json([], 403);
        }

        [$from, $to] = $this->getDateRange($request);
        [$prevFrom, $prevTo] = $this->getPreviousDateRange($from, $to);
        $repo = $this->analyticsFor($site);
        $sections = $site->public_sections ?: self::ALL_SECTIONS;

        $visitors      = $repo->getUniqueVisitors($site->site_id, $from, $to);
        $prevVisitors  = $repo->getUniqueVisitors($site->site_id, $prevFrom, $prevTo);
        $sessions      = $repo->getTotalSessions($site->site_id, $from, $to);
        $prevSessions  = $repo->getTotalSessions($site->site_id, $prevFrom, $prevTo);
        $pageviews     = $repo->getTotalPageviews($site->site_id, $from, $to);
        $prevPageviews = $repo->getTotalPageviews($site->site_id, $prevFrom, $prevTo);
        $bounceRate    = $repo->getBounceRate($site->site_id, $from, $to);
        $prevBounce    = $repo->getBounceRate($site->site_id, $prevFrom, $prevTo);
        $avgDuration   = $repo->getAvgVisitDuration($site->site_id, $from, $to);
        $prevDuration  = $repo->getAvgVisitDuration($site->site_id, $prevFrom, $prevTo);

        return response()->json([
            'stats' => [
                ['metric' => 'visitors',  'label' => 'Unique Visitors', 'value' => number_format($visitors),            'trend' => $this->trend($visitors, $prevVisitors),   'icon' => 'people'],
                ['metric' => 'sessions',  'label' => 'Total Sessions',  'value' => number_format($sessions),            'trend' => $this->trend($sessions, $prevSessions),   'icon' => 'cursor'],
                ['metric' => 'pageviews', 'label' => 'Total Pageviews', 'value' => number_format($pageviews),           'trend' => $this->trend($pageviews, $prevPageviews), 'icon' => 'eye'],
                ['metric' => 'bounce',    'label' => 'Bounce Rate',     'value' => $bounceRate . '%',                   'trend' => -$this->trend($bounceRate, $prevBounce),  'icon' => 'arrow-return-left'],
                ['metric' => 'duration',  'label' => 'Avg Duration',    'value' => $this->formatDuration($avgDuration), 'trend' => $this->trend($avgDuration, $prevDuration), 'icon' => 'clock'],
            ],
            'topPages'    => in_array('pages',       $sections) ? $repo->getTopPages($site->site_id, $from, $to)           : [],
            'sources'     => in_array('sources',     $sections) ? $repo->getTrafficSources($site->site_id, $from, $to)     : [],
            'locations'   => in_array('locations',   $sections) ? $repo->getLocations($site->site_id, $from, $to)          : [],
            'devices'     => in_array('devices',     $sections) ? $repo->getDevices($site->site_id, $from, $to)            : [],
            'browsers'    => in_array('browsers',    $sections) ? $repo->getBrowsers($site->site_id, $from, $to)           : [],
            'os'          => in_array('os',          $sections) ? $repo->getOperatingSystems($site->site_id, $from, $to)   : [],
            'resolutions' => in_array('resolutions', $sections) ? $repo->getScreenResolutions($site->site_id, $from, $to)  : [],
        ]);
    }

    public function chart(string $token, Request $request)
    {
        $site = $this->findPublicSite($token);

        if ($site->public_password && !session('pub_unlocked_' . $token)) {
            return response()->json([], 403);
        }

        [$from, $to] = $this->getDateRange($request);

        return response()->json(
            $this->analyticsFor($site)->getVisitorsOverTime($site->site_id, $from, $to, $site->timezone)
        );
    }

    private function findPublicSite(string $token): Site
    {
        return Site::withoutUserScope()
            ->where('public_token', $token)
            ->where('is_public', true)
            ->firstOrFail();
    }

    private function getDateRange(Request $request): array
    {
        if ($request->filled('from') && $request->filled('to')) {
            return [
                Carbon::parse($request->from)->startOfDay()->toDateTimeString(),
                Carbon::parse($request->to)->endOfDay()->toDateTimeString(),
            ];
        }

        return match ($request->input('range', 'last7days')) {
            'today'      => [now()->startOfDay()->toDateTimeString(), now()->endOfDay()->toDateTimeString()],
            'yesterday'  => [now()->subDay()->startOfDay()->toDateTimeString(), now()->subDay()->endOfDay()->toDateTimeString()],
            'last24h'    => [now()->subHours(24)->toDateTimeString(), now()->toDateTimeString()],
            'last30days' => [now()->subDays(30)->startOfDay()->toDateTimeString(), now()->endOfDay()->toDateTimeString()],
            'this_month' => [now()->startOfMonth()->toDateTimeString(), now()->endOfDay()->toDateTimeString()],
            'last_month' => [now()->subMonth()->startOfMonth()->toDateTimeString(), now()->subMonth()->endOfMonth()->endOfDay()->toDateTimeString()],
            default      => [now()->subDays(7)->startOfDay()->toDateTimeString(), now()->endOfDay()->toDateTimeString()],
        };
    }

    private function getPreviousDateRange(string $from, string $to): array
    {
        $fromDate = Carbon::parse($from);
        return [
            $fromDate->copy()->subDays($fromDate->diffInDays(Carbon::parse($to)) + 1)->toDateTimeString(),
            $fromDate->copy()->subDay()->endOfDay()->toDateTimeString(),
        ];
    }

    private function analyticsFor(Site $site): AnalyticsRepository
    {
        $repo = $this->analytics;
        if (!$site->track_subdomains) {
            $repo = $repo->withoutSubdomains($site->domain);
        }
        return $repo;
    }

    private function formatDuration(int $seconds): string
    {
        return sprintf('%d:%02d', floor($seconds / 60), $seconds % 60);
    }

    private function trend(int|float $current, int|float $previous): float
    {
        if ($previous == 0) {
            return $current > 0 ? 100 : 0;
        }
        return round((($current - $previous) / $previous) * 100, 1);
    }
}
