<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Models;

use App\Traits\BelongsToUser;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Site extends Model
{
    use HasFactory, SoftDeletes, BelongsToUser;

    protected $fillable = [
        'user_id',
        'name',
        'domain',
        'site_id',
        'timezone',
        'is_active',
        'track_subdomains',
    ];

    protected function casts(): array
    {
        return [
            'is_active'        => 'boolean',
            'track_subdomains' => 'boolean',
        ];
    }

    protected static function booted(): void
    {
        static::creating(fn ($site) => $site->site_id = $site->site_id ?: 'SA-' . strtoupper(Str::random(13)));
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function getTrackingSnippetAttribute(): string
    {
        return '<script defer data-site-id="' . e($this->site_id) . '" src="' . url('/js/tracker.js') . '"></script>';
    }

    public function setDomainAttribute(string $value): void
    {
        $value = preg_replace('#^https?://#', '', $value);
        $value = rtrim($value, '/');

        $this->attributes['domain'] = $value;
    }
}
