<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Models;

use App\Traits\BelongsToUser;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Site extends Model
{
    use HasFactory, SoftDeletes, BelongsToUser;

    protected $fillable = [
        'user_id',
        'name',
        'domain',
        'site_id',
        'timezone',
        'is_active',
        'track_subdomains',
        'track_bots',
        'is_public',
        'public_token',
        'public_password',
        'public_sections',
        'gsc_refresh_token',
        'gsc_access_token',
        'gsc_token_expires_at',
        'gsc_site_url',
    ];

    protected function casts(): array
    {
        return [
            'is_active'           => 'boolean',
            'track_subdomains'    => 'boolean',
            'track_bots'          => 'boolean',
            'is_public'           => 'boolean',
            'public_sections'     => 'array',
            'gsc_token_expires_at' => 'datetime',
        ];
    }

    protected static function booted(): void
    {
        static::creating(fn ($site) => $site->site_id = $site->site_id ?: 'ST-' . strtoupper(Str::random(13)));
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function funnels(): HasMany
    {
        return $this->hasMany(Funnel::class);
    }

    public function goals(): HasMany
    {
        return $this->hasMany(Goal::class);
    }

    public function getTrackingSnippetAttribute(): string
    {
        // Single static script for every site. Site identification via data-site-id;
        // heatmap activation discovered at runtime via /api/site-config.
        $src = url('/js/tracker.js');

        return '<script async src="' . $src . '" data-site-id="' . e($this->site_id) . '"></script>';
    }

    /**
     * @deprecated Bot detection is now automatic via UA + IP-range verification.
     * Returns the same snippet as the regular tracker — no extra pixel needed.
     */
    public function getBotTrackingSnippetAttribute(): string
    {
        return $this->tracking_snippet;
    }

    public function setDomainAttribute(string $value): void
    {
        $value = preg_replace('#^https?://#', '', $value);
        $value = rtrim($value, '/');

        $this->attributes['domain'] = $value;
    }
}
