<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Models;

use Database\Factories\UserFactory;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable;

    protected $fillable = [
        'name', 'email', 'password', 'is_admin',
        'stripe_customer_id', // Cloud billing — column added by cloud package migration
    ];

    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_secret',
        'two_factor_recovery_codes',
        'ga_access_token',
        'ga_refresh_token',
    ];

    protected function casts(): array
    {
        return [
            'email_verified_at'         => 'datetime',
            'two_factor_confirmed_at'   => 'datetime',
            'ga_token_expires_at'       => 'datetime',
            'password'                  => 'hashed',
            'is_admin'                  => 'boolean',
            'two_factor_secret'         => 'encrypted',
            'two_factor_recovery_codes' => 'encrypted:array',
            'ga_access_token'           => 'encrypted',
            'ga_refresh_token'          => 'encrypted',
        ];
    }

    public function hasActiveSubscription(): bool
    {
        return $this->subscription()?->isActive() ?? false;
    }

    public function sites(): HasMany
    {
        return $this->hasMany(Site::class);
    }

    /** Active subscription — only resolves when the cloud package is installed. */
    public function subscription()
    {
        if (!class_exists(\Statalog\Cloud\Models\Subscription::class)) {
            return null;
        }
        return $this->hasOne(\Statalog\Cloud\Models\Subscription::class)
            ->whereIn('status', ['active', 'trialing', 'incomplete', 'past_due'])
            ->latest();
    }

    /** Convenience accessor for the user's current plan via their active subscription. */
    public function getPlanAttribute()
    {
        return $this->subscription?->plan;
    }

    public function settings(): HasMany
    {
        return $this->hasMany(Setting::class);
    }

    public function hasTwoFactorEnabled(): bool
    {
        return !is_null($this->two_factor_confirmed_at);
    }
}
