<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Providers;

use App\Repositories\AnalyticsRepository;
use App\Services\BotFilterService;
use App\Services\GeoIpService;
use App\Services\SettingsService;
use App\Services\UserAgentService;
use App\Services\VisitorService;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->singleton(AnalyticsRepository::class);
        $this->app->singleton(BotFilterService::class);
        $this->app->singleton(GeoIpService::class);
        $this->app->singleton(UserAgentService::class);
        $this->app->singleton(VisitorService::class);
        $this->app->singleton(SettingsService::class);
    }

    public function boot(): void
    {
        //
    }
}
