<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Repositories;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class AnalyticsRepository
{
    protected string $host;
    protected int $port;
    protected string $database;
    protected string $username;
    protected string $password;
    protected bool $excludeSubdomains = false;
    protected string $registeredDomain = '';
    protected string $hostnameFilter = '';
    protected bool $includeBots = false;
    protected bool $onlyBots = false;

    public function __construct()
    {
        $this->host     = (string) config('clickhouse.connection.host', '127.0.0.1');
        $this->port     = (int) config('clickhouse.connection.port', 8123);
        $this->database = (string) config('clickhouse.connection.options.database', 'default');
        $this->username = (string) config('clickhouse.connection.username', 'default');
        $this->password = (string) config('clickhouse.connection.password', '');
    }

    /**
     * Return a clone of the repository that filters out subdomain hits.
     * $domain is the registered domain (e.g. "example.com").
     */
    public function withoutSubdomains(string $domain): static
    {
        $clone = clone $this;
        $clone->excludeSubdomains = true;
        $clone->registeredDomain = ltrim(preg_replace('/^www\./i', '', strtolower($domain)), '');
        return $clone;
    }

    /** Filter to a specific hostname (overrides subdomain exclude filter). */
    public function forHostname(string $hostname): static
    {
        $clone = clone $this;
        $clone->hostnameFilter = strtolower(trim($hostname));
        return $clone;
    }

    /** Include bot traffic in results (default: excluded). */
    public function includeBots(): static
    {
        $clone = clone $this;
        $clone->includeBots = true;
        return $clone;
    }

    /** Return ONLY bot traffic in results. */
    public function onlyBots(): static
    {
        $clone = clone $this;
        $clone->includeBots = true;
        $clone->onlyBots = true;
        return $clone;
    }

    /** Returns the extra WHERE fragment for hostname/subdomain + bot filtering. */
    protected function sd(): string
    {
        $clause = '';

        if ($this->hostnameFilter !== '') {
            $h = addslashes($this->hostnameFilter);
            $clause .= " AND hostname = '{$h}'";
        } elseif ($this->excludeSubdomains && $this->registeredDomain !== '') {
            $d = addslashes($this->registeredDomain);
            $clause .= " AND (hostname = '{$d}' OR hostname = 'www.{$d}' OR hostname = '')";
        }

        if ($this->onlyBots) {
            $clause .= ' AND is_bot = 1';
        } elseif (!$this->includeBots) {
            $clause .= ' AND is_bot = 0';
        }

        return $clause;
    }

    /** Returns cache key suffix for hostname/subdomain + bot filtering. */
    protected function sdKey(): string
    {
        $suffix = '';
        if ($this->hostnameFilter !== '') {
            $suffix .= ':hn=' . $this->hostnameFilter;
        } elseif ($this->excludeSubdomains) {
            $suffix .= ':nosd';
        }
        if ($this->onlyBots) {
            $suffix .= ':obots';
        } elseif ($this->includeBots) {
            $suffix .= ':wbots';
        }
        return $suffix;
    }

    /** Returns distinct hostnames for a site in the given date range. */
    public function getDistinctHostnames(string $siteId, string $from, string $to): array
    {
        return $this->queryWithCache(
            "hostnames:{$siteId}:{$from}:{$to}", 300,
            "SELECT hostname, count() as hits FROM pageviews WHERE site_id = :site_id AND timestamp >= :from AND timestamp <= :to AND hostname != '' GROUP BY hostname ORDER BY hits DESC LIMIT 50",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    protected function query(string $sql, array $params = []): array
    {
        foreach ($params as $key => $value) {
            $escaped = is_string($value) ? "'" . addslashes($value) . "'" : $value;
            $sql = str_replace(':' . $key, (string) $escaped, $sql);
        }

        try {
            $response = Http::withBasicAuth($this->username, $this->password)
                ->timeout(config('clickhouse.timeout', 10))
                ->withBody($sql . ' FORMAT JSON', 'text/plain')
                ->post("http://{$this->host}:{$this->port}/?database={$this->database}");
        } catch (\Throwable $e) {
            // ClickHouse unreachable (dev environment without it running, network blip, etc).
            // Log once per request and return empty — the admin area stays usable with zero data.
            Log::warning('ClickHouse query failed: ' . $e->getMessage());
            return [];
        }

        if ($response->failed()) {
            Log::warning('ClickHouse query returned non-2xx: ' . $response->status() . ' ' . $response->body());
            return [];
        }

        $data = $response->json();
        return $data['data'] ?? [];
    }

    protected function queryWithCache(string $key, int $seconds, string $sql, array $params = []): array
    {
        return Cache::remember($key, $seconds, function () use ($sql, $params) {
            return $this->query($sql, $params);
        });
    }

    // --- Dashboard Stats ---

    public function getUniqueVisitors(string $siteId, string $from, string $to): int
    {
        $rows = $this->queryWithCache(
            "visitors:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT uniq(visitor_id) as cnt FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
        return (int) ($rows[0]['cnt'] ?? 0);
    }

    public function getTotalSessions(string $siteId, string $from, string $to): int
    {
        $rows = $this->queryWithCache(
            "sessions:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT uniq(session_id) as cnt FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
        return (int) ($rows[0]['cnt'] ?? 0);
    }

    public function getTotalPageviews(string $siteId, string $from, string $to): int
    {
        $rows = $this->queryWithCache(
            "pageviews:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT count() as cnt FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to AND url != ''",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
        return (int) ($rows[0]['cnt'] ?? 0);
    }

    public function getBounceRate(string $siteId, string $from, string $to): float
    {
        $rows = $this->queryWithCache(
            "bounce:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT
                countIf(pv_count = 1) as bounced,
                count() as total
            FROM (
                SELECT session_id, count() as pv_count
                FROM pageviews
                WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to
                GROUP BY session_id
            )",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
        $total = (int) ($rows[0]['total'] ?? 0);
        if ($total === 0) {
            return 0.0;
        }
        return round(((int) ($rows[0]['bounced'] ?? 0) / $total) * 100, 1);
    }

    public function getAvgVisitDuration(string $siteId, string $from, string $to): int
    {
        $rows = $this->queryWithCache(
            "avgduration:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT avg(duration) as avg_dur FROM (
                SELECT session_id, greatest(dateDiff('second', min(timestamp), max(timestamp)), max(visit_duration)) as duration
                FROM pageviews
                WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to AND session_id != ''
                GROUP BY session_id
                HAVING duration > 0
            )",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
        return (int) ($rows[0]['avg_dur'] ?? 0);
    }

    // --- Chart Data ---

    public function getVisitorsOverTime(string $siteId, string $from, string $to, string $timezone = 'UTC'): array
    {
        return $this->queryWithCache(
            "visitors_chart:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT
                date,
                sum(visitors) as visitors,
                sum(pageviews) as pageviews,
                count() as sessions,
                round(countIf(pv_count = 1) * 100.0 / count(), 1) as bounce,
                toInt32(avg(duration)) as duration
            FROM (
                SELECT
                    session_id,
                    toDate(min(timestamp), :tz) as date,
                    uniq(visitor_id) as visitors,
                    countIf(url != '') as pv_count,
                    countIf(url != '') as pageviews,
                    greatest(dateDiff('second', min(timestamp), max(timestamp)), max(visit_duration)) as duration
                FROM pageviews
                WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to
                GROUP BY session_id
            )
            GROUP BY date
            ORDER BY date",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to, 'tz' => $timezone]
        );
    }

    // --- Detail Cards ---

    public function getTopPages(string $siteId, string $from, string $to, int $limit = 10): array
    {
        return $this->queryWithCache(
            "top_pages:{$siteId}:{$from}:{$to}:{$limit}" . $this->sdKey(), 300,
            "SELECT url, count() as pageviews FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to GROUP BY url ORDER BY pageviews DESC LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getPageBreakdown(string $siteId, string $from, string $to, int $limit = 100): array
    {
        return $this->queryWithCache(
            "page_breakdown:{$siteId}:{$from}:{$to}:{$limit}" . $this->sdKey(), 300,
            "SELECT
                path,
                count() AS pageviews,
                uniq(visitor_id) AS unique_visitors,
                round(avg(is_bounce) * 100) AS bounce_rate,
                round(avgIf(visit_duration, visit_duration > 0)) AS avg_time
             FROM pageviews
             WHERE site_id = :site_id" . $this->sd() . "
               AND timestamp >= :from AND timestamp <= :to
               AND path != ''
             GROUP BY path
             ORDER BY pageviews DESC
             LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getLocationsFull(string $siteId, string $from, string $to, int $limit = 100): array
    {
        return $this->queryWithCache(
            "locations_full:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT country, uniq(visitor_id) AS visitors, count() AS pageviews
             FROM pageviews
             WHERE site_id = :site_id" . $this->sd() . "
               AND timestamp >= :from AND timestamp <= :to
               AND country != ''
             GROUP BY country
             ORDER BY visitors DESC
             LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getByCity(string $siteId, string $from, string $to, int $limit = 100): array
    {
        return $this->queryWithCache(
            "by_city:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT country, city, uniq(visitor_id) AS visitors
             FROM pageviews
             WHERE site_id = :site_id" . $this->sd() . "
               AND timestamp >= :from AND timestamp <= :to
               AND city != ''
             GROUP BY country, city
             ORDER BY visitors DESC
             LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getHourlyHeatmap(string $siteId, string $from, string $to, string $timezone = 'UTC'): array
    {
        return $this->queryWithCache(
            "hourly_heatmap:{$siteId}:{$from}:{$to}:{$timezone}" . $this->sdKey(), 300,
            "SELECT
                toDayOfWeek(toTimeZone(timestamp, :tz)) AS day_of_week,
                toHour(toTimeZone(timestamp, :tz))      AS hour,
                count() AS pageviews
             FROM pageviews
             WHERE site_id = :site_id" . $this->sd() . "
               AND timestamp >= :from AND timestamp <= :to
             GROUP BY day_of_week, hour
             ORDER BY day_of_week, hour",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to, 'tz' => $timezone]
        );
    }

    public function getTrafficSources(string $siteId, string $from, string $to, int $limit = 10): array
    {
        return $this->queryWithCache(
            "sources:{$siteId}:{$from}:{$to}:{$limit}" . $this->sdKey(), 300,
            "SELECT
                if(referrer = '', 'Direct', domain(referrer)) as source,
                uniq(session_id) as visits
            FROM pageviews
            WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to
            GROUP BY source
            ORDER BY visits DESC
            LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getLocations(string $siteId, string $from, string $to, int $limit = 10): array
    {
        return $this->queryWithCache(
            "locations:{$siteId}:{$from}:{$to}:{$limit}" . $this->sdKey(), 300,
            "SELECT country, uniq(visitor_id) as visitors FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to GROUP BY country ORDER BY visitors DESC LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getDevices(string $siteId, string $from, string $to): array
    {
        return $this->queryWithCache(
            "devices:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT device_type as device, uniq(visitor_id) as visitors FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to GROUP BY device_type ORDER BY visitors DESC",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getBrowsers(string $siteId, string $from, string $to, int $limit = 10): array
    {
        return $this->queryWithCache(
            "browsers:{$siteId}:{$from}:{$to}:{$limit}" . $this->sdKey(), 300,
            "SELECT browser, uniq(visitor_id) as visitors FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to GROUP BY browser ORDER BY visitors DESC LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getOperatingSystems(string $siteId, string $from, string $to, int $limit = 10): array
    {
        return $this->queryWithCache(
            "os:{$siteId}:{$from}:{$to}:{$limit}" . $this->sdKey(), 300,
            "SELECT os, uniq(visitor_id) as visitors FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to GROUP BY os ORDER BY visitors DESC LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getScreenResolutions(string $siteId, string $from, string $to, int $limit = 10): array
    {
        return $this->queryWithCache(
            "resolutions:{$siteId}:{$from}:{$to}:{$limit}" . $this->sdKey(), 300,
            "SELECT concat(toString(screen_width), 'x', toString(screen_height)) as screen_resolution, count() as cnt FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to AND screen_width > 0 GROUP BY screen_resolution ORDER BY cnt DESC LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    // --- Live Stats ---

    public function getLiveVisitors(string $siteId, int $minutes = 30, ?string $hostname = null): array
    {
        $hf = $hostname ? " AND domain(url) = :hostname" : '';
        $params = ['site_id' => $siteId];
        if ($hostname) {
            $params['hostname'] = $hostname;
        }

        $sql = "SELECT
                toStartOfMinute(timestamp) as minute,
                uniq(visitor_id) as visitors
            FROM pageviews
            WHERE site_id = :site_id" . $this->sd() . " AND url != '' AND timestamp >= now() - INTERVAL {$minutes} MINUTE{$hf}
            GROUP BY minute
            ORDER BY minute";

        return $this->query($sql, $params);
    }

    public function getLiveVisitorCount(string $siteId, int $minutes = 30, ?string $hostname = null): int
    {
        $hf = $hostname ? " AND domain(url) = :hostname" : '';
        $params = ['site_id' => $siteId];
        if ($hostname) {
            $params['hostname'] = $hostname;
        }

        $rows = $this->query(
            "SELECT uniq(visitor_id) as cnt FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND url != '' AND timestamp >= now() - INTERVAL {$minutes} MINUTE{$hf}",
            $params
        );
        return (int) ($rows[0]['cnt'] ?? 0);
    }

    public function getRecentVisits(string $siteId, int $limit = 20, ?string $hostname = null): array
    {
        $hf = $hostname ? " AND domain(url) = :hostname" : '';
        $params = ['site_id' => $siteId];
        if ($hostname) {
            $params['hostname'] = $hostname;
        }

        return $this->query(
            "SELECT timestamp, url, country, city, device_type, browser, referrer, utm_source, utm_medium, utm_campaign FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND url != ''{$hf} ORDER BY timestamp DESC LIMIT {$limit}",
            $params
        );
    }

    public function getLiveSubdomains(string $siteId): array
    {
        return $this->query(
            "SELECT DISTINCT domain(url) as hostname FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND url != '' AND timestamp >= now() - INTERVAL 60 MINUTE ORDER BY hostname",
            ['site_id' => $siteId]
        );
    }

    // --- UTM Campaigns ---

    public function getCampaigns(string $siteId, string $from, string $to): array
    {
        return $this->queryWithCache(
            "campaigns:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT
                utm_campaign,
                utm_source,
                utm_medium,
                uniq(session_id) as visits,
                uniq(visitor_id) as unique_visitors,
                count() as pageviews,
                round(countIf(is_bounce = 1) * 100.0 / count(), 1) as bounce_rate,
                round(avg(visit_duration)) as avg_duration
            FROM pageviews
            WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to AND (utm_campaign != '' OR utm_source != '' OR utm_medium != '')
            GROUP BY utm_campaign, utm_source, utm_medium
            ORDER BY visits DESC",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getCampaignDrilldown(string $siteId, string $campaign, string $from, string $to): array
    {
        return $this->queryWithCache(
            "campaign_drill:{$siteId}:{$campaign}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT
                utm_term,
                utm_content,
                uniq(session_id) as visits,
                uniq(visitor_id) as unique_visitors,
                count() as pageviews
            FROM pageviews
            WHERE site_id = :site_id" . $this->sd() . " AND utm_campaign = :campaign AND timestamp >= :from AND timestamp <= :to
            GROUP BY utm_term, utm_content
            ORDER BY visits DESC",
            ['site_id' => $siteId, 'campaign' => $campaign, 'from' => $from, 'to' => $to]
        );
    }

    // --- Entry & Exit Pages ---

    public function getEntryPages(string $siteId, string $from, string $to, int $limit = 50): array
    {
        return $this->queryWithCache(
            "entry:{$siteId}:{$from}:{$to}:{$limit}" . $this->sdKey(), 300,
            "SELECT
                entry_page,
                count() as sessions,
                round(countIf(pv_count = 1) * 100.0 / count(), 1) as bounce_rate,
                round(avg(duration)) as avg_duration
            FROM (
                SELECT
                    session_id,
                    argMin(entry_page, timestamp) as entry_page,
                    countIf(url != '') as pv_count,
                    greatest(dateDiff('second', min(timestamp), max(timestamp)), max(visit_duration)) as duration
                FROM pageviews
                WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to
                GROUP BY session_id
            )
            WHERE entry_page != ''
            GROUP BY entry_page
            ORDER BY sessions DESC
            LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getExitPages(string $siteId, string $from, string $to, int $limit = 50): array
    {
        return $this->queryWithCache(
            "exit:{$siteId}:{$from}:{$to}:{$limit}" . $this->sdKey(), 300,
            "SELECT
                exit_page,
                count() as exits,
                round(countIf(pv_count = 1) * 100.0 / count(), 1) as bounce_rate,
                round(avg(duration)) as avg_duration
            FROM (
                SELECT
                    session_id,
                    argMax(exit_page, timestamp) as exit_page,
                    countIf(url != '') as pv_count,
                    greatest(dateDiff('second', min(timestamp), max(timestamp)), max(visit_duration)) as duration
                FROM pageviews
                WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to
                GROUP BY session_id
            )
            WHERE exit_page != ''
            GROUP BY exit_page
            ORDER BY exits DESC
            LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    // --- Visit Depth ---

    public function getVisitDepth(string $siteId, string $from, string $to): array
    {
        return $this->queryWithCache(
            "depth:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT
                multiIf(pv_count = 1, '1', pv_count = 2, '2', pv_count = 3, '3', pv_count <= 5, '4-5', pv_count <= 10, '6-10', '10+') as depth,
                count() as sessions
            FROM (
                SELECT session_id, countIf(url != '') as pv_count
                FROM pageviews
                WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to
                GROUP BY session_id
            )
            GROUP BY depth
            ORDER BY depth",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    // --- New vs Returning ---

    public function getNewVsReturning(string $siteId, string $from, string $to): array
    {
        return $this->queryWithCache(
            "newret:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT
                if(is_new_visitor = 1, 'New', 'Returning') as segment,
                uniq(visitor_id) as visitors,
                uniq(session_id) as sessions,
                countIf(url != '') as pageviews,
                round(avg(duration)) as avg_duration
            FROM (
                SELECT
                    session_id,
                    visitor_id,
                    any(is_new_visitor) as is_new_visitor,
                    countIf(url != '') as pv_count,
                    greatest(dateDiff('second', min(timestamp), max(timestamp)), max(visit_duration)) as duration
                FROM pageviews
                WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to
                GROUP BY session_id, visitor_id
            )
            GROUP BY segment",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getNewVsReturningOverTime(string $siteId, string $from, string $to, string $timezone = 'UTC'): array
    {
        return $this->queryWithCache(
            "newret_chart:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT
                toDate(timestamp, :tz) as date,
                countIf(is_new_visitor = 1) as new_visitors,
                countIf(is_new_visitor = 0) as returning_visitors
            FROM pageviews
            WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to
            GROUP BY date
            ORDER BY date",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to, 'tz' => $timezone]
        );
    }

    // --- Time on Page ---

    public function getTimeOnPage(string $siteId, string $from, string $to, int $limit = 50): array
    {
        return $this->queryWithCache(
            "timeonpage:{$siteId}:{$from}:{$to}:{$limit}" . $this->sdKey(), 300,
            "SELECT
                p.url as url,
                round(avg(d.duration)) as avg_time,
                count() as pageviews
            FROM (
                SELECT url, session_id
                FROM pageviews
                WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to AND url != ''
            ) p
            LEFT JOIN (
                SELECT session_id, max(visit_duration) as duration
                FROM pageviews
                WHERE site_id = :site_id AND timestamp >= :from AND timestamp <= :to AND visit_duration > 0
                GROUP BY session_id
            ) d ON p.session_id = d.session_id
            GROUP BY p.url
            ORDER BY pageviews DESC
            LIMIT {$limit}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    // --- Performance ---

    public function getPerformanceOverview(string $siteId, string $from, string $to): array
    {
        $rows = $this->queryWithCache(
            "perf_overview:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT
                avgIf(network_time,        network_time > 0)        AS avg_network,
                avgIf(server_time,         server_time > 0)         AS avg_server,
                avgIf(transfer_time,       transfer_time > 0)       AS avg_transfer,
                avgIf(dom_processing_time, dom_processing_time > 0) AS avg_dom_processing,
                avgIf(dom_completion_time, dom_completion_time > 0) AS avg_dom_completion,
                avgIf(on_load_time,        on_load_time > 0)        AS avg_on_load,
                avgIf(load_time,           load_time > 0)           AS avg_load
            FROM pageviews
            WHERE site_id = :site_id" . $this->sd() . " AND url != '' AND timestamp >= :from AND timestamp <= :to",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
        return $rows[0] ?? [];
    }

    public function getPerformanceOverTime(string $siteId, string $from, string $to, string $timezone = 'UTC'): array
    {
        return $this->queryWithCache(
            "perf_time:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT
                toDate(timestamp, :tz) AS date,
                avgIf(network_time,        network_time > 0)        AS avg_network,
                avgIf(server_time,         server_time > 0)         AS avg_server,
                avgIf(transfer_time,       transfer_time > 0)       AS avg_transfer,
                avgIf(dom_processing_time, dom_processing_time > 0) AS avg_dom_processing,
                avgIf(dom_completion_time, dom_completion_time > 0) AS avg_dom_completion,
                avgIf(on_load_time,        on_load_time > 0)        AS avg_on_load,
                avgIf(load_time,           load_time > 0)           AS avg_load
            FROM pageviews
            WHERE site_id = :site_id" . $this->sd() . " AND url != '' AND timestamp >= :from AND timestamp <= :to
            GROUP BY date ORDER BY date ASC",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to, 'tz' => $timezone]
        );
    }

    // --- Visitor Map ---

    public function getLiveVisitorMap(string $siteId, int $minutes = 30): array
    {
        return $this->query(
            "SELECT
                latitude,
                longitude,
                any(country) AS country,
                any(city)    AS city,
                count()      AS hits
            FROM pageviews
            WHERE site_id = :site_id
              AND is_bot = 0
              AND latitude != 0
              AND longitude != 0
              AND timestamp >= now() - INTERVAL :minutes MINUTE
            GROUP BY latitude, longitude
            ORDER BY hits DESC
            LIMIT 500",
            ['site_id' => $siteId, 'minutes' => $minutes]
        );
    }

    public function getVisitorMapPoints(string $siteId, string $from, string $to): array
    {
        return $this->queryWithCache(
            "map_points:{$siteId}:{$from}:{$to}" . $this->sdKey(), 300,
            "SELECT
                latitude,
                longitude,
                any(country) AS country,
                any(city)    AS city,
                count()      AS hits
            FROM pageviews
            WHERE site_id = :site_id" . $this->sd() . "
              AND latitude != 0
              AND longitude != 0
              AND url != ''
              AND timestamp >= :from
              AND timestamp <= :to
            GROUP BY latitude, longitude
            ORDER BY hits DESC
            LIMIT 2000",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    // --- Visitor Log ---

    public function getVisitorLog(string $siteId, string $from, string $to, int $limit = 25, int $offset = 0): array
    {
        return $this->query(
            "SELECT
                session_id,
                visitor_id,
                min(timestamp) AS first_seen,
                any(country) AS country,
                any(city) AS city,
                any(device_type) AS device_type,
                any(browser) AS browser,
                any(os) AS os,
                countIf(url != '') AS pages,
                greatest(dateDiff('second', min(timestamp), max(timestamp)), max(visit_duration)) AS duration,
                argMinIf(url, timestamp, url != '') AS entry_page,
                anyIf(referrer_domain, referrer_domain != '') AS referrer,
                anyIf(utm_source, utm_source != '') AS utm_source,
                anyIf(utm_medium, utm_medium != '') AS utm_medium,
                anyIf(utm_campaign, utm_campaign != '') AS utm_campaign
            FROM pageviews
            WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to
            GROUP BY session_id, visitor_id
            HAVING pages > 0
            ORDER BY first_seen DESC
            LIMIT {$limit} OFFSET {$offset}",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function countVisitorSessions(string $siteId, string $from, string $to): int
    {
        $rows = $this->query(
            "SELECT uniq(session_id) AS total FROM pageviews
             WHERE site_id = :site_id" . $this->sd() . " AND url != '' AND timestamp >= :from AND timestamp <= :to",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
        return (int) ($rows[0]['total'] ?? 0);
    }

    // --- Funnel ---

    public function getFunnelData(string $siteId, array $stepPaths, string $from, string $to): array
    {
        $results = [];
        foreach ($stepPaths as $i => $path) {
            if ($i === 0) {
                $rows = $this->query(
                    "SELECT uniq(visitor_id) as visitors FROM pageviews WHERE site_id = :site_id" . $this->sd() . " AND url LIKE :path AND timestamp >= :from AND timestamp <= :to",
                    ['site_id' => $siteId, 'path' => '%' . $path . '%', 'from' => $from, 'to' => $to]
                );
                $results[] = (int) ($rows[0]['visitors'] ?? 0);
            } else {
                $prevPaths = array_slice($stepPaths, 0, $i + 1);
                $conditions = [];
                foreach ($prevPaths as $p) {
                    $conditions[] = "countIf(url LIKE '%" . addslashes($p) . "%') > 0";
                }
                $having = implode(' AND ', $conditions);
                $rows = $this->query(
                    "SELECT count() as visitors FROM (
                        SELECT session_id
                        FROM pageviews
                        WHERE site_id = :site_id" . $this->sd() . " AND timestamp >= :from AND timestamp <= :to
                        GROUP BY session_id
                        HAVING {$having}
                    )",
                    ['site_id' => $siteId, 'from' => $from, 'to' => $to]
                );
                $results[] = (int) ($rows[0]['visitors'] ?? 0);
            }
        }
        return $results;
    }

    // --- Custom Events ---

    public function getCustomEvents(string $siteId, string $from, string $to): array
    {
        return $this->queryWithCache(
            "events:{$siteId}:{$from}:{$to}", 300,
            "SELECT
                event_name,
                count() as total,
                uniq(visitor_id) as unique_visitors,
                min(timestamp) as first_seen,
                max(timestamp) as last_seen
            FROM custom_events
            WHERE site_id = :site_id AND timestamp >= :from AND timestamp <= :to
            GROUP BY event_name
            ORDER BY total DESC",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getEventOverTime(string $siteId, string $eventName, string $from, string $to, string $timezone = 'UTC'): array
    {
        return $this->queryWithCache(
            "event_chart:{$siteId}:{$eventName}:{$from}:{$to}", 300,
            "SELECT
                toDate(timestamp, :tz) as date,
                count() as occurrences,
                uniq(visitor_id) as unique_visitors
            FROM custom_events
            WHERE site_id = :site_id AND event_name = :event_name AND timestamp >= :from AND timestamp <= :to
            GROUP BY date
            ORDER BY date",
            ['site_id' => $siteId, 'event_name' => $eventName, 'from' => $from, 'to' => $to, 'tz' => $timezone]
        );
    }

    public function getEventProperties(string $siteId, string $eventName, string $from, string $to): array
    {
        return $this->queryWithCache(
            "event_props:{$siteId}:{$eventName}:{$from}:{$to}", 300,
            "SELECT properties, count() as cnt FROM custom_events WHERE site_id = :site_id AND event_name = :event_name AND timestamp >= :from AND timestamp <= :to AND properties != '' GROUP BY properties ORDER BY cnt DESC LIMIT 100",
            ['site_id' => $siteId, 'event_name' => $eventName, 'from' => $from, 'to' => $to]
        );
    }

    // --- Admin Stats ---

    /**
     * Returns pageviews, unique visitors, and sessions for multiple sites in one ClickHouse query.
     * Returns array keyed by site_id.
     */
    public function getSiteStatsBulk(array $siteIds, string $from, string $to): array
    {
        if (empty($siteIds)) {
            return [];
        }

        $placeholders = implode(',', array_map(fn ($id) => "'" . addslashes($id) . "'", $siteIds));

        $rows = $this->query(
            "SELECT site_id, count() as pageviews, uniq(visitor_id) as visitors, uniq(session_id) as sessions
             FROM pageviews
             WHERE site_id IN ({$placeholders}) AND timestamp >= :from AND timestamp <= :to
             GROUP BY site_id",
            ['from' => $from, 'to' => $to]
        );

        $result = [];
        foreach ($rows as $row) {
            $result[$row['site_id']] = [
                'pageviews' => (int) $row['pageviews'],
                'visitors'  => (int) $row['visitors'],
                'sessions'  => (int) $row['sessions'],
            ];
        }
        return $result;
    }

    /**
     * Returns today/this_month/last_month hit counts for each site_id in one query.
     * Result: ['SA-XXX' => ['today' => N, 'this_month' => N, 'last_month' => N], ...]
     */
    public function getSiteHitCounts(array $siteIds): array
    {
        if (empty($siteIds)) {
            return [];
        }

        $ids = implode("','", array_map(fn ($id) => preg_replace('/[^A-Za-z0-9\-]/', '', $id), $siteIds));

        $rows = $this->query(
            "SELECT
                site_id,
                countIf(timestamp >= toStartOfDay(now())) as today,
                countIf(timestamp >= toStartOfMonth(now())) as this_month,
                countIf(timestamp >= toStartOfMonth(subtractMonths(now(), 1)) AND timestamp < toStartOfMonth(now())) as last_month
            FROM pageviews
            WHERE site_id IN ('{$ids}') AND url != ''
            GROUP BY site_id"
        );

        $result = array_fill_keys($siteIds, ['today' => 0, 'this_month' => 0, 'last_month' => 0]);
        foreach ($rows as $row) {
            $result[$row['site_id']] = [
                'today'      => (int) $row['today'],
                'this_month' => (int) $row['this_month'],
                'last_month' => (int) $row['last_month'],
            ];
        }
        return $result;
    }

    public function getTotalPageviewsAllSites(): int
    {
        $rows = $this->query("SELECT count() as cnt FROM pageviews");
        return (int) ($rows[0]['cnt'] ?? 0);
    }

    public function getTodayEventsCount(): int
    {
        $rows = $this->query("SELECT count() as cnt FROM pageviews WHERE timestamp >= today()");
        return (int) ($rows[0]['cnt'] ?? 0);
    }

    public function getSiteTodayHits(string $siteId): int
    {
        $rows = $this->query(
            "SELECT count() as cnt FROM pageviews WHERE site_id = :site_id AND timestamp >= today()",
            ['site_id' => $siteId]
        );
        return (int) ($rows[0]['cnt'] ?? 0);
    }

    // --- ClickHouse Write (for event ingestion only from job) ---

    public function insertPageview(array $data): bool
    {
        $columns = implode(', ', array_keys($data));
        $values = implode(', ', array_map(function ($v) {
            if (is_int($v) || is_float($v)) {
                return $v;
            }
            return "'" . addslashes((string) $v) . "'";
        }, array_values($data)));

        $sql = "INSERT INTO pageviews ({$columns}) VALUES ({$values})";

        $response = Http::withBasicAuth($this->username, $this->password)
            ->timeout(config('clickhouse.timeout', 10))
            ->withBody($sql, 'text/plain')
            ->post("http://{$this->host}:{$this->port}/?database={$this->database}");

        return $response->successful();
    }

    public function insertCustomEvent(array $data): bool
    {
        $columns = implode(', ', array_keys($data));
        $values = implode(', ', array_map(function ($v) {
            if (is_int($v) || is_float($v)) {
                return $v;
            }
            return "'" . addslashes((string) $v) . "'";
        }, array_values($data)));

        $sql = "INSERT INTO custom_events ({$columns}) VALUES ({$values})";

        $response = Http::withBasicAuth($this->username, $this->password)
            ->timeout(config('clickhouse.timeout', 10))
            ->withBody($sql, 'text/plain')
            ->post("http://{$this->host}:{$this->port}/?database={$this->database}");

        return $response->successful();
    }

    public function insertError(array $data): bool
    {
        $columns = implode(', ', array_keys($data));
        $values = implode(', ', array_map(function ($v) {
            if (is_int($v) || is_float($v)) {
                return $v;
            }
            return "'" . addslashes((string) $v) . "'";
        }, array_values($data)));

        $sql = "INSERT INTO js_errors ({$columns}) VALUES ({$values})";

        $response = Http::withBasicAuth($this->username, $this->password)
            ->timeout(config('clickhouse.timeout', 10))
            ->withBody($sql, 'text/plain')
            ->post("http://{$this->host}:{$this->port}/?database={$this->database}");

        return $response->successful();
    }

    public function getErrorStats(string $siteId, string $from, string $to): array
    {
        $rows = $this->query(
            "SELECT
                count() AS total_errors,
                uniq(fingerprint) AS unique_errors,
                uniq(visitor_id) AS affected_visitors
             FROM js_errors
             WHERE site_id = :site_id
               AND timestamp BETWEEN :from AND :to",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );

        $pv = $this->query(
            "SELECT count() AS c FROM pageviews
             WHERE site_id = :site_id AND timestamp BETWEEN :from AND :to",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );

        $pageviews = (int) ($pv[0]['c'] ?? 0);
        $total     = (int) ($rows[0]['total_errors'] ?? 0);

        return [
            'total_errors'      => $total,
            'unique_errors'     => (int) ($rows[0]['unique_errors'] ?? 0),
            'affected_visitors' => (int) ($rows[0]['affected_visitors'] ?? 0),
            'error_rate'        => $pageviews > 0 ? round(($total / $pageviews) * 100, 2) : 0,
        ];
    }

    public function getErrorsOverTime(string $siteId, string $from, string $to, string $timezone = 'UTC'): array
    {
        return $this->query(
            "SELECT
                toDate(timestamp, :tz) AS day,
                error_type,
                count() AS cnt
             FROM js_errors
             WHERE site_id = :site_id AND timestamp BETWEEN :from AND :to
             GROUP BY day, error_type
             ORDER BY day ASC",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to, 'tz' => $timezone]
        );
    }

    public function getErrorGroups(string $siteId, string $from, string $to): array
    {
        return $this->query(
            "SELECT
                fingerprint,
                any(message) AS message,
                any(source)  AS source,
                any(line)    AS line,
                any(error_type) AS error_type,
                count() AS total,
                uniq(visitor_id) AS affected_visitors,
                min(timestamp) AS first_seen,
                max(timestamp) AS last_seen
             FROM js_errors
             WHERE site_id = :site_id AND timestamp BETWEEN :from AND :to
             GROUP BY fingerprint
             ORDER BY total DESC
             LIMIT 200",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    public function getErrorDetail(string $siteId, string $fingerprint, string $from, string $to): array
    {
        $summary = $this->query(
            "SELECT
                any(message) AS message,
                any(source)  AS source,
                any(line)    AS line,
                any(col)     AS col,
                any(stack)   AS stack,
                any(error_type) AS error_type,
                count() AS total,
                uniq(visitor_id) AS affected_visitors,
                min(timestamp) AS first_seen,
                max(timestamp) AS last_seen
             FROM js_errors
             WHERE site_id = :site_id
               AND fingerprint = :fingerprint
               AND timestamp BETWEEN :from AND :to",
            ['site_id' => $siteId, 'fingerprint' => $fingerprint, 'from' => $from, 'to' => $to]
        );

        $breakdown = function (string $column) use ($siteId, $fingerprint, $from, $to) {
            return $this->query(
                "SELECT {$column} AS name, count() AS cnt
                 FROM js_errors
                 WHERE site_id = :site_id
                   AND fingerprint = :fingerprint
                   AND timestamp BETWEEN :from AND :to
                 GROUP BY {$column}
                 ORDER BY cnt DESC
                 LIMIT 20",
                ['site_id' => $siteId, 'fingerprint' => $fingerprint, 'from' => $from, 'to' => $to]
            );
        };

        $recent = $this->query(
            "SELECT timestamp, url, browser, os, country
             FROM js_errors
             WHERE site_id = :site_id
               AND fingerprint = :fingerprint
               AND timestamp BETWEEN :from AND :to
             ORDER BY timestamp DESC
             LIMIT 50",
            ['site_id' => $siteId, 'fingerprint' => $fingerprint, 'from' => $from, 'to' => $to]
        );

        return [
            'summary'     => $summary[0] ?? null,
            'by_browser'  => $breakdown('browser'),
            'by_os'       => $breakdown('os'),
            'by_device'   => $breakdown('device_type'),
            'by_url'      => $breakdown('url'),
            'recent'      => $recent,
        ];
    }

    /** Count of hits grouped by bot_name (bots only). */
    public function getBotBreakdown(string $siteId, string $from, string $to): array
    {
        return $this->query(
            "SELECT bot_name AS name, count() AS hits, uniq(visitor_id) AS visitors
             FROM pageviews
             WHERE site_id = :site_id
               AND is_bot = 1
               AND timestamp BETWEEN :from AND :to
               AND bot_name != ''
             GROUP BY bot_name
             ORDER BY hits DESC
             LIMIT 50",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    /** Bot hits per day, used for the stacked line chart on the Bots page. */
    public function getBotsOverTime(string $siteId, string $from, string $to, string $timezone = 'UTC'): array
    {
        return $this->query(
            "SELECT toDate(timestamp, :tz) AS day, bot_name, count() AS hits
             FROM pageviews
             WHERE site_id = :site_id
               AND is_bot = 1
               AND timestamp BETWEEN :from AND :to
             GROUP BY day, bot_name
             ORDER BY day ASC",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to, 'tz' => $timezone]
        );
    }

    /** Top pages hit by bots — what are they crawling most? */
    public function getBotTopPages(string $siteId, string $from, string $to): array
    {
        return $this->query(
            "SELECT path AS url, count() AS hits, uniq(bot_name) AS distinct_bots
             FROM pageviews
             WHERE site_id = :site_id
               AND is_bot = 1
               AND timestamp BETWEEN :from AND :to
               AND path != ''
             GROUP BY path
             ORDER BY hits DESC
             LIMIT 50",
            ['site_id' => $siteId, 'from' => $from, 'to' => $to]
        );
    }

    /**
     * Hard-deletes every row for a site across pageviews, custom_events, js_errors.
     * Uses ClickHouse lightweight deletes — fast and async at the table level.
     */
    public function deleteAllForSite(string $siteId): void
    {
        foreach (['pageviews', 'custom_events', 'js_errors'] as $table) {
            $sql = "DELETE FROM {$table} WHERE site_id = '" . addslashes($siteId) . "'";
            try {
                Http::withBasicAuth($this->username, $this->password)
                    ->timeout(config('clickhouse.timeout', 10))
                    ->withBody($sql, 'text/plain')
                    ->post("http://{$this->host}:{$this->port}/?database={$this->database}");
            } catch (\Throwable $e) {
                Log::warning("ClickHouse purge failed for {$table}/{$siteId}: " . $e->getMessage());
            }
        }
    }

    public function updatePageviewDuration(string $siteId, string $sessionId, string $url, int $duration): void
    {
        $sql = "ALTER TABLE pageviews UPDATE visit_duration = {$duration}"
            . " WHERE site_id = '" . addslashes($siteId) . "'"
            . " AND session_id = '" . addslashes($sessionId) . "'"
            . " AND url = '" . addslashes($url) . "'"
            . " AND visit_duration = 0";

        Http::withBasicAuth($this->username, $this->password)
            ->timeout(config('clickhouse.timeout', 10))
            ->withBody($sql, 'text/plain')
            ->post("http://{$this->host}:{$this->port}/?database={$this->database}");
    }

    public function purgeOlderThan(string $siteId, string $table, string $cutoffDate): int
    {
        $rows = $this->query(
            "SELECT count() as cnt FROM {$table} WHERE site_id = :site_id AND toDate(timestamp) < :cutoff",
            ['site_id' => $siteId, 'cutoff' => $cutoffDate]
        );
        $count = (int) ($rows[0]['cnt'] ?? 0);

        if ($count > 0) {
            $sql = "ALTER TABLE {$table} DELETE WHERE site_id = :site_id AND toDate(timestamp) < :cutoff";
            $this->query($sql, ['site_id' => $siteId, 'cutoff' => $cutoffDate]);
        }

        return $count;
    }

    public function testConnection(): bool
    {
        try {
            $response = Http::withBasicAuth($this->username, $this->password)
                ->timeout(5)
                ->get("http://{$this->host}:{$this->port}/ping");
            return $response->successful();
        } catch (\Exception $e) {
            return false;
        }
    }
}
