<?php
/**
 * Statalog - Open source web analytics.
 * Powerful, privacy-first web analytics you can trust. No cookies, fully GDPR-compliant.
 * https://statalog.com
 *
 * Copyright (c) Host Server SRL (Statalog)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Statalog)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@statalog.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Jobs;

use App\Models\Site;
use App\Repositories\AnalyticsRepository;
use App\Services\BotFilterService;
use App\Services\GeoIpService;
use App\Services\UserAgentService;
use App\Services\VisitorService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Cache;

class ProcessAnalyticsHit implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public int $tries = 2;
    public int $backoff = 5;

    public function __construct(
        public readonly array $payload,
        public readonly string $ip,
        public readonly string $userAgent,
        public readonly bool $dnt,
    ) {}

    public function handle(
        BotFilterService $botFilter,
        GeoIpService $geoIp,
        UserAgentService $uaParser,
        VisitorService $visitor,
        AnalyticsRepository $analytics,
    ): void {
        $botInfo = $botFilter->identify($this->userAgent, $this->dnt);
        $isBot   = $botInfo['is_bot'];
        $botName = $botInfo['name'];

        $siteId = trim($this->payload['site_id'] ?? '');
        if ($siteId === '') {
            return;
        }
        $site = $this->getSiteData($siteId);
        if (!$site) {
            return;
        }

        // Drop bots entirely unless this site opts in to store them.
        if ($isBot && !$site['track_bots']) {
            return;
        }

        $type = $this->payload['type'] ?? 'pageview';

        $rawUrl   = $this->payload['url'] ?? '';
        $parsed   = parse_url($rawUrl);
        $hostname = $parsed['host'] ?? '';

        if ($type !== 'heartbeat' && !$this->isDomainAllowed($hostname, $site)) {
            return;
        }
        $sessionId = $this->payload['session_id'] ?? '';

        $visitorId = $visitor->anonymise($this->ip, $this->userAgent, $siteId);

        if ($type === 'error') {
            $message     = (string) ($this->payload['message'] ?? '');
            $source      = (string) ($this->payload['source'] ?? '');
            $line        = (int)    ($this->payload['line'] ?? 0);
            $col         = (int)    ($this->payload['col'] ?? 0);
            $stack       = mb_substr((string) ($this->payload['stack'] ?? ''), 0, 2000);
            $errorType   = (string) ($this->payload['error_type'] ?? 'error');
            $fingerprint = substr(sha1($message . '|' . $source . '|' . $line), 0, 16);

            $geo    = $geoIp->lookup($this->ip);
            $uaData = $uaParser->parse($this->userAgent, (int) ($this->payload['screen_width'] ?? 0));

            $analytics->insertError([
                'site_id'     => $siteId,
                'timestamp'   => date('Y-m-d H:i:s'),
                'fingerprint' => $fingerprint,
                'error_type'  => $errorType,
                'message'     => mb_substr($message, 0, 500),
                'source'      => mb_substr($source, 0, 500),
                'line'        => $line,
                'col'         => $col,
                'stack'       => $stack,
                'url'         => $rawUrl,
                'hostname'    => $hostname,
                'browser'     => $uaData['browser'],
                'os'          => $uaData['os'],
                'device_type' => $uaData['device_type'],
                'country'     => $geo['country'],
                'visitor_id'  => $visitorId,
                'is_bot'      => $isBot ? 1 : 0,
                'bot_name'    => $botName,
            ]);
            return;
        }

        if ($type === 'event') {
            $geo    = $geoIp->lookup($this->ip);
            $uaData = $uaParser->parse($this->userAgent, (int) ($this->payload['screen_width'] ?? 0));

            $analytics->insertCustomEvent([
                'site_id'     => $siteId,
                'timestamp'   => date('Y-m-d H:i:s'),
                'session_id'  => $sessionId,
                'visitor_id'  => $visitorId,
                'event_name'  => $this->payload['event_name'] ?? '',
                'properties'  => $this->payload['properties'] ?? '',
                'url'         => $rawUrl,
                'hostname'    => $hostname,
                'country'     => $geo['country'],
                'device_type' => $uaData['device_type'],
                'is_bot'      => $isBot ? 1 : 0,
                'bot_name'    => $botName,
            ]);
            return;
        }

        if ($type === 'heartbeat') {
            $duration = (int) ($this->payload['duration'] ?? 0);
            if ($sessionId !== '' && $duration > 0) {
                $analytics->insertPageview([
                    'site_id'        => $siteId,
                    'timestamp'      => date('Y-m-d H:i:s'),
                    'session_id'     => $sessionId,
                    'visitor_id'     => $visitorId,
                    'url'            => '',
                    'visit_duration' => $duration,
                    'is_bot'         => $isBot ? 1 : 0,
                    'bot_name'       => $botName,
                ]);
            }
            return;
        }

        $path           = $parsed['path'] ?? '';
        $queryStr       = $parsed['query'] ?? '';
        $referrer       = $this->payload['referrer'] ?? '';
        $referrerDomain = '';
        if ($referrer !== '') {
            $referrerDomain = parse_url($referrer, PHP_URL_HOST) ?? '';
        }

        $screenWidth  = (int) ($this->payload['screen_width'] ?? 0);
        $uaData       = $uaParser->parse($this->userAgent, $screenWidth);
        $geo          = $geoIp->lookup($this->ip);
        $isBounce     = $this->resolveIsBounce($sessionId, $siteId);
        $isNewVisitor = $this->resolveIsNewVisitor($visitorId, $siteId);

        $analytics->insertPageview([
            'site_id'         => $siteId,
            'timestamp'       => date('Y-m-d H:i:s'),
            'session_id'      => $sessionId,
            'visitor_id'      => $visitorId,
            'hostname'        => $hostname,
            'url'             => $rawUrl,
            'path'            => $path,
            'query_string'    => $queryStr,
            'referrer'        => $referrer,
            'referrer_domain' => $referrerDomain,
            'browser'         => $uaData['browser'],
            'browser_version' => $uaData['browser_version'],
            'os'              => $uaData['os'],
            'os_version'      => $uaData['os_version'],
            'device_type'     => $uaData['device_type'],
            'screen_width'    => $screenWidth,
            'screen_height'   => (int) ($this->payload['screen_height'] ?? 0),
            'country'         => $geo['country'],
            'region'          => $geo['region'],
            'city'            => $geo['city'],
            'utm_source'      => $this->payload['utm_source'] ?? '',
            'utm_medium'      => $this->payload['utm_medium'] ?? '',
            'utm_campaign'    => $this->payload['utm_campaign'] ?? '',
            'utm_content'     => $this->payload['utm_content'] ?? '',
            'utm_term'        => $this->payload['utm_term'] ?? '',
            'load_time'       => (int) ($this->payload['load_time'] ?? 0),
            'visit_duration'  => 0,
            'is_bounce'       => $isBounce,
            'is_new_visitor'  => $isNewVisitor,
            'entry_page'      => $rawUrl,
            'exit_page'       => $rawUrl,
            'is_bot'          => $isBot ? 1 : 0,
            'bot_name'        => $botName,
        ]);
    }

    protected function getSiteData(string $siteId): ?array
    {
        return Cache::remember("site_data:{$siteId}", 300, function () use ($siteId) {
            $site = Site::withoutUserScope()
                ->where('site_id', $siteId)
                ->where('is_active', true)
                ->first();
            if (!$site) {
                return null;
            }
            return [
                'domain'           => $site->domain,
                'track_subdomains' => (bool) $site->track_subdomains,
                'track_bots'       => (bool) $site->track_bots,
            ];
        });
    }

    protected function isDomainAllowed(string $hostname, array $site): bool
    {
        if ($hostname === '') {
            return false;
        }

        $domain = strtolower($site['domain']);
        $host   = strtolower(preg_replace('/^www\./', '', $hostname));
        $base   = preg_replace('/^www\./', '', $domain);

        if ($host === $base) {
            return true;
        }

        if ($site['track_subdomains'] && str_ends_with($host, '.' . $base)) {
            return true;
        }

        return false;
    }

    private function resolveIsBounce(string $sessionId, string $siteId): int
    {
        if ($sessionId === '') {
            return 1;
        }
        $key    = "session:{$siteId}:{$sessionId}";
        $exists = Cache::has($key);
        Cache::put($key, 1, 1800);
        return $exists ? 0 : 1;
    }

    private function resolveIsNewVisitor(string $visitorId, string $siteId): int
    {
        if ($visitorId === '') {
            return 1;
        }
        $key    = "visitor_seen:{$siteId}:{$visitorId}";
        $exists = Cache::has($key);
        Cache::put($key, 1, 2592000);
        return $exists ? 0 : 1;
    }
}
